/* This program generated by adt-translate.lisp */ 
/* Datafile = ADT-Situation/Sit-q-i2-dist1-default-1000 */

#include <stdio.h>

#define DEFAULT_SIZE 99    /* define array size */

main () {

/* Initial variable declarations */
int firstint;
firstint = 0;
int null;
null = 0;
int firstbool;
firstbool = 0;
float firstreal;
firstreal = 0.0;
char firstchar;
firstchar = 0;

/* Initial array declarations */
int firstarrayi[DEFAULT_SIZE];
char firstarrayc[DEFAULT_SIZE];
float firstarrayr[DEFAULT_SIZE];
int firstarrayb[DEFAULT_SIZE];

/* Initial inline function protoypes */
int   checkIntInt    (int   x);
int   checkIntBool   (int   x);
int   checkIntChar   (char  x);
int   checkIntReal   (float x);
float checkRealInt   (int   x);
float checkRealBool  (int   x);
float checkRealChar  (char  x);
float checkRealReal  (float x);
int   checkBoolInt   (int   x);
int   checkBoolBool  (int   x);
int   checkBoolChar  (char  x);
int   checkBoolReal  (float x);
char  checkCharInt   (int   x);
char  checkCharBool  (int   x);
char  checkCharChar  (char  x);
char  checkCharReal  (float x);

/* Code parsing commenced ... here. */

int var_name632;
var_name632 = 0;
int var_name1282;
var_name1282 = 0;
var_name632 = checkIntInt(var_name1282);
int var_name80;
var_name80 = 0;
int var_name7;
var_name7 = 0;
var_name80 = checkIntInt(var_name7);
int var_name106;
var_name106 = 0;
int var_name239;
var_name239 = 0;
var_name106 = checkIntInt(var_name239);
int var_name1417;
int var_name1469[124];
int var_name343;
var_name343 = 0;
var_name343 = checkIntReal(* firstarrayr);
int var_name817;
int var_name131;
var_name131 = 0;
firstarrayb[var_name131] = 0;
int var_name158;
var_name158 = 0;
int var_name214;
var_name214 = 0;
var_name158 = checkIntInt(var_name214);
float var_name591[3];
float var_name1668[38];
int var_name17;
var_name17 = 0;
var_name17 = 0;
var_name7 = checkIntReal(* firstarrayr);
int var_name988[DEFAULT_SIZE];
int var_name1107;
var_name1107 = 0;
 ++var_name988[var_name1107];
int var_name21;
var_name21 = 0;
int var_name493;
var_name493 = 0;
int var_name1381;
var_name1381 = 0;
var_name1381 = !(var_name21 == var_name493);
int var_name1572;
var_name1572 = 0;
while( var_name1572 != 0 )
{   /* begin block block1570 */
int var_name42;
var_name42 = 0;
int var_name228;
var_name228 = 0;
var_name228 = !(var_name214 == var_name42);
int var_name145;
var_name145 = 0;
 ++var_name145;
}   /* end block block1570 */
int var_name231;
var_name231 = 0;
int var_name149;
var_name149 = 0;
var_name231 = checkIntInt(var_name149);
firstint = checkIntInt(var_name17);
int var_name1467;
{   /* begin block block1247 */
int var_name830;
var_name830 = 0;
int var_name1093;
var_name1093 = 0;
var_name830 = checkIntInt(var_name1093);
int var_name425;
var_name425 = 0;
int var_name601;
var_name601 = 0;
var_name425 = checkIntInt(var_name601);
int var_name277;
var_name277 = 0;
printf(">%i<\n", var_name277);
printf(">%i<\n", firstint);
}   /* end block block1247 */
int var_name996[DEFAULT_SIZE];
var_name1107 = var_name996[firstint];
 ++firstarrayb[var_name7];
int var_name67;
var_name67 = 0;
int var_name1335;
var_name1335 = 0;
var_name67 = checkIntInt(var_name1335);
int var_name1420[111];
int var_name713;
var_name713 = 0;
for( var_name713 = 62; var_name713 < 100; var_name713++ )
{   /* begin block block710 */
firstreal = firstarrayr[var_name67];
char var_name145;
}   /* end block block710 */
int var_name666;
var_name666 = 0;
printf(">%i<\n", var_name666);
printf(">%i<\n", var_name713);
{   /* begin block block915 */
int var_name962;
var_name962 = 0;
for( var_name962 = 23; var_name962 > 33;var_name962-- )
{   /* begin block block524 */
{   /* begin block block959 */
var_name80 = !(firstarrayc[0] == var_name343);
}   /* end block block959 */
}   /* end block block524 */
int var_name277;
var_name277 = 0;
printf(">%i<\n", var_name277);
printf(">%i<\n", var_name962);
/* ........... adtq1_a 46 100  decl array a char 99   ........... */
char a[99];
}   /* end block block915 */
int var_name225;
var_name225 = 0;
int var_name686;
var_name686 = 0;
var_name225 = checkIntInt(var_name686);
int var_name491;
var_name491 = 0;
int var_name436;
var_name436 = 0;
var_name491 = checkIntInt(var_name436);
{   /* begin block block543 */
int var_name1273;
var_name1273 = 0;
int var_name519;
var_name519 = 0;
int var_name1284;
var_name1284 = 0;
var_name1284 = !(var_name1273 == var_name519);
int var_name84;
var_name84 = 0;
if( var_name84 != 0 )
{   /* begin block if_then222 */
int var_name48;
var_name48 = 0;
var_name48 = checkIntInt(var_name17);
}   /* end block if_then222 */
else {   /* begin ELSE block block654 */
int var_name1018;
var_name1018 = 0;
var_name1018 = checkIntInt(var_name632);
int var_name637;
var_name637 = 0;
printf(">%i<\n", var_name637);
printf(">%i<\n", firstint);
int var_name179;
var_name179 = 0;
int var_name223;
var_name223 = 0;
/* Warn: Assign 4: curpos = 59, body = var_name149 var_name179 var_name223  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
float var_name59;
}   /* end ELSE block block654 */
int var_name1018;
var_name1018 = 0;
var_name1018 = checkIntInt(var_name632);
int var_name637;
var_name637 = 0;
printf(">%i<\n", var_name637);
printf(">%i<\n", firstint);
int var_name179;
var_name179 = 0;
int var_name223;
var_name223 = 0;
/* Warn: Assign 4: curpos = 64, body = var_name149 var_name179 var_name223  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
float var_name59;
}   /* end block block543 */
int var_name145;
var_name145 = 0;
int var_name116;
var_name116 = 0;
int var_name596;
var_name596 = 0;
var_name596 = !(var_name145 == var_name116);
{   /* begin block block890 */
int var_name1018;
var_name1018 = 0;
int var_name601;
var_name601 = 0;
var_name1018 = checkIntInt(var_name601);
int var_name1136;
var_name1136 = 0;
var_name1136 = checkIntReal(* var_name591);
{   /* begin block block728 */
int var_name254;
var_name254 = 0;
int var_name504;
var_name504 = 0;
int var_name451;
var_name451 = 0;
var_name451 = !(var_name254 == var_name504);
int var_name688;
var_name688 = 0;
int var_name1101;
var_name1101 = 0;
var_name688 = var_name1101;
var_name149 = 0;
int var_name48;
var_name48 = 0;
var_name7 = checkIntInt(var_name48);
float var_name1563;
int var_name287;
var_name287 = 0;
 ++var_name287;
}   /* end block block728 */
var_name149 = 0;
int var_name1837;
var_name1837 = 0;
while( var_name1837 != 0 )
{   /* begin block block1835 */
int var_name688;
int var_name48;
var_name48 = 0;
var_name7 = checkIntInt(var_name48);
float var_name1563;
int var_name287;
var_name287 = 0;
 ++var_name287;
{   /* begin block block534 */
}   /* end block block534 */
}   /* end block block1835 */
while( var_name214 != 0 )
{   /* begin block block1206 */
}   /* end block block1206 */
}   /* end block block890 */
int var_name1158;
var_name1158 = 0;
int var_name367;
var_name367 = 0;
var_name1158 = checkIntInt(var_name367);
int var_name798;
var_name798 = 0;
var_name817 = var_name798;
var_name225 = 0;
int var_name69;
int var_name122;
var_name122 = 0;
int var_name160;
var_name160 = 0;
var_name122 = checkIntInt(var_name160);
int var_name84;
var_name84 = 0;
var_name84 = checkIntInt(var_name21);
int var_name1719;
int var_name1145;
var_name1145 = 0;
for( var_name1145 = 22; var_name1145 < 24; var_name1145++ )
{   /* begin block block1142 */
int var_name258;
var_name258 = 0;
 ++var_name258;
int var_name241[DEFAULT_SIZE];
int var_name311;
var_name311 = 0;
var_name17 = var_name241[var_name311];
printf(">%i<\n", var_name149);
printf(">%i<\n", firstint);
int var_name812;
var_name812 = 0;
int var_name1093;
var_name1093 = 0;
var_name812 = checkIntInt(var_name1093);
{   /* begin block block1316 */
char var_name1480;
var_name80 = 0;
 ++var_name149;
/* ........... adtq1_b 102 200  zero idx   ........... */
int idx;
idx = 0;
idx = 0;
}   /* end block block1316 */
var_name80 = 0;
 ++var_name149;
/* ........... adtq1_b 102 200  zero idx   ........... */
int idx;
idx = 0;
idx = 0;
}   /* end block block1142 */
int var_name912;
var_name912 = 0;
for( var_name912 = 11; var_name912 < 50; var_name912++ )
{   /* begin block block909 */
int var_name322;
var_name322 = 0;
int var_name465;
var_name465 = 0;
int var_name1389;
var_name1389 = 0;
var_name1389 = !(var_name322 == var_name465);
}   /* end block block909 */
int var_name637[DEFAULT_SIZE];
int var_name489;
var_name489 = 0;
var_name637[var_name489] = 0;
int var_name95;
var_name95 = 0;
firstreal = checkRealInt(var_name95);
int firstboolean;
firstboolean = 0;
while( firstboolean != 0 )
{   /* begin block block905 */
printf(">%i<\n", var_name436);
int var_name1766;
var_name1766 = 0;
if( var_name1766 != 0 )
{   /* begin block if_then223 */
printf(">%i<\n", var_name637[firstint]);
}   /* end block if_then223 */
else {   /* begin ELSE block block1764 */
{   /* begin block block1045 */
int var_name1032;
var_name1032 = 0;
int var_name812;
var_name812 = 0;
int var_name1065;
var_name1065 = 0;
var_name1065 = !(var_name1032 == var_name812);
int var_name204;
var_name204 = 0;
var_name106 = checkIntInt(var_name204);
int var_name99;
var_name99 = 0;
int var_name465;
var_name465 = 0;
var_name99 = checkIntInt(var_name465);
int var_name284;
var_name284 = 0;
int var_name707;
var_name707 = 0;
int var_name111;
var_name111 = 0;
var_name111 = !(var_name284 == var_name707);
}   /* end block block1045 */
}   /* end ELSE block block1764 */
int var_name1032;
var_name1032 = 0;
int var_name812;
var_name812 = 0;
int var_name1065;
var_name1065 = 0;
var_name1065 = !(var_name1032 == var_name812);
int var_name204;
var_name204 = 0;
var_name106 = checkIntInt(var_name204);
int var_name99;
var_name99 = 0;
int var_name465;
var_name465 = 0;
var_name99 = checkIntInt(var_name465);
int var_name284;
var_name284 = 0;
int var_name707;
var_name707 = 0;
int var_name111;
var_name111 = 0;
var_name111 = !(var_name284 == var_name707);
{   /* begin block block872 */
}   /* end block block872 */
}   /* end block block905 */
int var_name1136;
var_name1136 = 0;
int var_name1482;
var_name1482 = 0;
int var_name1538;
var_name1538 = 0;
var_name1538 = !(var_name1136 == var_name1482);
int var_name465;
int var_name179;
var_name179 = 0;
firstarrayi[var_name179] = 0;
{   /* begin block block251 */
float var_name1789;
int var_name621;
var_name621 = 0;
float var_name461;
var_name461 = 0;
var_name461 = var_name591[var_name621];
int var_name48;
var_name48 = 0;
var_name48 = firstarrayi[firstint];
int var_name1629;
var_name1629 = 0;
int var_name284;
var_name284 = 0;
var_name1629 = checkIntInt(var_name284);
int var_name1445;
var_name1445 = 0;
for( var_name1445 = 21; var_name1445 < 27; var_name1445++ )
{   /* begin block block1442 */
}   /* end block block1442 */
}   /* end block block251 */
int var_name1435;
var_name1435 = 0;
 ++var_name996[var_name1435];
int var_name475;
var_name475 = 0;
while( var_name475 != 0 )
{   /* begin block block473 */
}   /* end block block473 */
int var_name277;
var_name277 = 0;
int var_name513;
var_name513 = 0;
var_name277 = checkIntInt(var_name513);
printf(">%i<\n", firstint);
char var_name1661;
char var_name1332;
while( var_name69 != 0 )
{   /* begin block block295 */
int var_name554;
var_name554 = 0;
/* Warn: Assign 4: curpos = 169, body = var_name343 var_name554 var_name17  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
/* ........... adtq1_c 149 300  while result   ........... */
int result;
result = 0;
if( result != 0 )
{   /* begin block if_then224 */
int var_name1042;
var_name1042 = 0;
int var_name548;
var_name548 = 0;
var_name1042 = checkIntInt(var_name548);
}   /* end block if_then224 */
else {   /* begin ELSE block block1700 */
int var_name176;
var_name176 = 0;
var_name17 = checkIntInt(var_name176);
/* ........... adtq1_d 154 310  begin block1   ........... */
{   /* begin block block1 */
int var_name947;
var_name947 = 0;
printf(">%i<\n", var_name947);
printf(">%i<\n", firstint);
firstint = firstint;
 ++var_name131;
int var_name30;
var_name30 = 0;
var_name17 = firstarrayc[var_name30];
int var_name241;
var_name241 = 0;
var_name69 = !(firstarrayc[0] == var_name241);
printf(">%i<\n", var_name7);
int var_name583;
var_name583 = 0;
for( var_name583 = 16; var_name583 < 42; var_name583++ )
{   /* begin block block580 */
char var_name571;
 ++var_name145;
}   /* end block block580 */
char var_name571;
 ++var_name145;
int var_name322;
var_name322 = 0;
 ++firstarrayb[var_name322];
var_name67 = firstint;
int var_name48;
var_name48 = 0;
int var_name1480;
var_name1480 = 0;
/* Warn: Assign 4: curpos = 192, body = var_name277 var_name48 var_name1480  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
firstchar = checkCharInt(var_name116);
int var_name825;
var_name825 = 0;
int var_name1032;
var_name1032 = 0;
var_name1538 = !(var_name825 == var_name1032);
int var_name375;
int var_name1002;
var_name1002 = 0;
 ++var_name1002;
int var_name1052;
var_name1052 = 0;
var_name1052 = checkIntInt(var_name214);
int var_name845;
var_name845 = 0;
var_name571 = checkCharInt(var_name845);
var_name845 = checkIntInt(var_name436);
float var_name1832;
int var_name805[DEFAULT_SIZE];
int var_name605;
var_name605 = 0;
var_name605 = var_name805[var_name48];
int var_name258;
var_name258 = 0;
var_name258 = 0;
int var_name52;
var_name52 = 0;
int var_name1577;
var_name1577 = 0;
int var_name1684;
var_name1684 = 0;
var_name1684 = !(var_name52 == var_name1577);
int var_name611;
var_name611 = 0;
var_name611 = checkIntInt(var_name489);
int var_name681;
var_name681 = 0;
var_name681 = var_name681;
int var_name601;
var_name601 = 0;
var_name131 = checkIntInt(var_name601);
int var_name1185;
var_name1185 = 0;
/* Warn: Assign 3: curpos = 208, body = var_name1185 var_name571  */
/* Warn: Assign 3: type mismatch 1 & 2 = i & c */
var_name1185 = var_name571;
int var_name445;
var_name445 = 0;
firstarrayb[var_name445] = 0;
/* ........... adtq1_g 195 400  assign a idx elemb   ........... */
int a[DEFAULT_SIZE];
int idx;
idx = 0;
int elemb;
elemb = 0;
elemb = a[idx];
int var_name1191;
var_name1191 = 0;
var_name1191 = 0;
int var_name1721[DEFAULT_SIZE];
int var_name1363;
var_name1363 = 0;
var_name1363 = var_name1721[var_name7];
int var_name482;
var_name482 = 0;
int var_name1151;
var_name1151 = 0;
var_name482 = checkIntInt(var_name1151);
printf(">%i<\n", var_name845);
var_name465 = checkIntInt(var_name666);
int var_name109;
var_name109 = 0;
int var_name254;
var_name254 = 0;
var_name254 = !(var_name605 == var_name109);
int var_name1015;
var_name1015 = 0;
var_name95 = firstarrayc[var_name1015];
char var_name99;
var_name99 = 0;
var_name99 = firstarrayc[var_name67];
firstint = var_name7;
int var_name850;
var_name850 = 0;
int var_name1358;
var_name1358 = 0;
/* Warn: Assign 4: curpos = 221, body = var_name947 var_name850 var_name1358  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
printf(">%i<\n", var_name225);
int var_name42;
var_name42 = 0;
int var_name1516;
var_name1516 = 0;
var_name42 = checkIntInt(var_name1516);
int var_name1829[78];
int var_name548;
var_name548 = 0;
printf(">%i<\n", var_name548);
var_name231 = checkIntInt(var_name67);
int var_name626;
int var_name287;
var_name287 = 0;
printf(">%i<\n", var_name287);
int var_name1054;
var_name1054 = 0;
int var_name1689;
var_name1689 = 0;
var_name1689 = !(var_name1054 == firstchar);
int var_name1022;
var_name1022 = 0;
var_name1022 = checkIntInt(var_name601);
printf(">%4.2f<\n", firstarrayr[firstint]);
int var_name354;
var_name354 = 0;
firstint = checkIntInt(var_name354);
printf(">%i<\n", var_name225);
/* ........... adtq1_i 242 500  increment idx   ........... */
 ++idx;
var_name239 = 0;
int var_name13;
var_name13 = 0;
firstboolean = !(firstint == var_name13);
int var_name751;
var_name751 = 0;
var_name571 = checkCharInt(var_name751);
int var_name174;
printf(">%i<\n", var_name239);
printf(">%i<\n", firstint);
int var_name1111;
var_name1111 = 0;
printf(">%i<\n", var_name1111);
printf(">%i<\n", firstint);
int var_name393;
var_name393 = 0;
int var_name212;
var_name212 = 0;
var_name212 = !(var_name158 == var_name393);
int var_name1075;
var_name1075 = 0;
var_name611 = firstarrayr[var_name1075];
int var_name563;
var_name563 = 0;
var_name445 = var_name563;
char var_name1724;
int var_name59;
var_name59 = 0;
var_name59 = checkIntInt(var_name30);
int var_name77;
var_name77 = 0;
int var_name209;
var_name209 = 0;
int var_name1095;
var_name1095 = 0;
var_name1095 = !(var_name77 == var_name209);
int var_name673;
var_name673 = 0;
var_name673 = !(firstarrayb[0] == var_name277);
char var_name528;
int var_name351;
var_name351 = 0;
/* Warn: Assign 4: curpos = 249, body = var_name239 var_name554 var_name351  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
float var_name1255[159];
/* Warn: Assign 3: curpos = 251, body = firstreal var_name493  */
/* Warn: Assign 3: type mismatch 1 & 2 = r & i */
firstreal = var_name493;
/* Warn: Assign 4: curpos = 252, body = var_name666 var_name817 var_name1107  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
int var_name455;
var_name455 = 0;
int var_name1009;
var_name1009 = 0;
int var_name1266;
var_name1266 = 0;
var_name1266 = !(var_name455 == var_name1009);
int var_name812;
var_name812 = 0;
printf(">%i<\n", var_name812);
int var_name698;
var_name698 = 0;
int var_name467;
var_name467 = 0;
int var_name753;
var_name753 = 0;
var_name753 = !(var_name698 == var_name467);
 ++var_name30;
char var_name731;
int var_name284;
var_name284 = 0;
var_name1358 = !(var_name1052 == var_name284);
}   /* end block block1 */
{   /* begin block block587 */
char var_name571;
 ++var_name145;
int var_name322;
var_name322 = 0;
 ++firstarrayb[var_name322];
var_name67 = firstint;
int var_name48;
var_name48 = 0;
int var_name1480;
var_name1480 = 0;
/* Warn: Assign 4: curpos = 266, body = var_name277 var_name48 var_name1480  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
}   /* end block block587 */
int var_name322;
var_name322 = 0;
 ++firstarrayb[var_name322];
var_name67 = firstint;
int var_name48;
var_name48 = 0;
int var_name1480;
var_name1480 = 0;
/* Warn: Assign 4: curpos = 270, body = var_name277 var_name48 var_name1480  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
}   /* end ELSE block block1700 */
firstchar = checkCharInt(var_name116);
int var_name825;
var_name825 = 0;
int var_name1032;
var_name1032 = 0;
var_name1538 = !(var_name825 == var_name1032);
int var_name375;
int var_name1002;
var_name1002 = 0;
 ++var_name1002;
int var_name1052;
var_name1052 = 0;
var_name1052 = checkIntInt(var_name214);
int var_name571;
var_name571 = 0;
int var_name845;
var_name845 = 0;
var_name571 = checkIntInt(var_name845);
var_name845 = checkIntInt(var_name436);
float var_name1832;
int var_name805[DEFAULT_SIZE];
int var_name48;
var_name48 = 0;
int var_name605;
var_name605 = 0;
var_name605 = var_name805[var_name48];
int var_name258;
var_name258 = 0;
var_name258 = 0;
int var_name52;
var_name52 = 0;
int var_name1577;
var_name1577 = 0;
int var_name1684;
var_name1684 = 0;
var_name1684 = !(var_name52 == var_name1577);
int var_name611;
var_name611 = 0;
var_name611 = checkIntInt(var_name489);
int var_name681;
var_name681 = 0;
var_name681 = var_name681;
int var_name601;
var_name601 = 0;
var_name131 = checkIntInt(var_name601);
for( var_name798 = 12; var_name798 > 12;var_name798-- )
{   /* begin block block795 */
int var_name1185;
var_name1185 = 0;
var_name1185 = var_name571;
int var_name1451;
var_name1451 = 0;
for( var_name1451 = 92; var_name1451 > 96;var_name1451-- )
{   /* begin block block1448 */
int var_name445;
var_name445 = 0;
firstarrayb[var_name445] = 0;
int var_name1676;
var_name1676 = 0;
if( var_name1676 != 0 )
{   /* begin block if_then225 */
/* ........... adtq1_g 195 400  assign a idx elemb   ........... */
int a[DEFAULT_SIZE];
int idx;
idx = 0;
int elemb;
elemb = 0;
elemb = a[idx];
}   /* end block if_then225 */
else {   /* begin ELSE block block501 */
int var_name1191;
var_name1191 = 0;
var_name1191 = 0;
}   /* end ELSE block block501 */
int var_name1191;
var_name1191 = 0;
var_name1191 = 0;
{   /* begin block block1674 */
int var_name1721[DEFAULT_SIZE];
int var_name1363;
var_name1363 = 0;
var_name1363 = var_name1721[var_name7];
int var_name482;
var_name482 = 0;
int var_name1151;
var_name1151 = 0;
var_name482 = checkIntInt(var_name1151);
}   /* end block block1674 */
int var_name1721[DEFAULT_SIZE];
int var_name1363;
var_name1363 = 0;
var_name1363 = var_name1721[var_name7];
int var_name482;
var_name482 = 0;
int var_name1151;
var_name1151 = 0;
var_name482 = checkIntInt(var_name1151);
}   /* end block block1448 */
}   /* end block block795 */
printf(">%i<\n", var_name845);
var_name465 = checkIntInt(var_name666);
int var_name109;
var_name109 = 0;
int var_name254;
var_name254 = 0;
var_name254 = !(var_name605 == var_name109);
int var_name1015;
var_name1015 = 0;
var_name95 = firstarrayc[var_name1015];
char var_name99;
var_name99 = 0;
var_name99 = firstarrayc[var_name67];
firstint = var_name7;
int var_name42;
var_name42 = 0;
while( var_name42 != 0 )
{   /* begin block block303 */
int var_name947[DEFAULT_SIZE];
int var_name850;
var_name850 = 0;
int var_name1358;
var_name1358 = 0;
var_name1358 = var_name947[var_name850];
}   /* end block block303 */
printf(">%i<\n", var_name225);
{   /* begin block block1621 */
int var_name1516;
var_name1516 = 0;
var_name42 = checkIntInt(var_name1516);
int var_name1829[78];
int var_name548;
var_name548 = 0;
printf(">%i<\n", var_name548);
while( var_name42 != 0 )
{   /* begin block block869 */
int var_name860;
var_name860 = 0;
while( var_name860 != 0 )
{   /* begin block block1639 */
var_name231 = checkIntInt(var_name67);
}   /* end block block1639 */
var_name231 = checkIntInt(var_name67);
}   /* end block block869 */
{   /* begin block block186 */
int var_name626;
int var_name287;
var_name287 = 0;
printf(">%i<\n", var_name287);
int var_name1054;
var_name1054 = 0;
int var_name1689;
var_name1689 = 0;
var_name1689 = !(var_name1054 == firstchar);
int var_name1022;
var_name1022 = 0;
var_name1022 = checkIntInt(var_name601);
}   /* end block block186 */
int var_name626;
int var_name287;
var_name287 = 0;
printf(">%i<\n", var_name287);
int var_name1054;
var_name1054 = 0;
int var_name1689;
var_name1689 = 0;
var_name1689 = !(var_name1054 == firstchar);
int var_name540;
var_name540 = 0;
while( var_name540 != 0 )
{   /* begin block block538 */
int var_name1022;
var_name1022 = 0;
var_name1022 = checkIntInt(var_name601);
printf(">%4.2f<\n", firstarrayr[firstint]);
}   /* end block block538 */
printf(">%4.2f<\n", firstarrayr[firstint]);
{   /* begin block block183 */
}   /* end block block183 */
}   /* end block block1621 */
int var_name354;
var_name354 = 0;
firstint = checkIntInt(var_name354);
printf(">%i<\n", var_name225);
/* ........... adtq1_i 242 500  increment idx   ........... */
int idx;
idx = 0;
 ++idx;
var_name239 = 0;
int var_name13;
var_name13 = 0;
firstboolean = !(firstint == var_name13);
int var_name751;
var_name751 = 0;
var_name571 = checkIntInt(var_name751);
int var_name174;
printf(">%i<\n", var_name239);
printf(">%i<\n", firstint);
int var_name1111;
var_name1111 = 0;
printf(">%i<\n", var_name1111);
printf(">%i<\n", firstint);
int var_name393;
var_name393 = 0;
int var_name212;
var_name212 = 0;
var_name212 = !(var_name158 == var_name393);
int var_name745;
var_name745 = 0;
for( var_name745 = 9; var_name745 < 70; var_name745++ )
{   /* begin block block742 */
int var_name1075;
var_name1075 = 0;
var_name611 = firstarrayr[var_name1075];
}   /* end block block742 */
int var_name445;
var_name445 = 0;
int var_name563;
var_name563 = 0;
var_name445 = var_name563;
char var_name1724;
{   /* begin block block235 */
int var_name59;
var_name59 = 0;
int var_name30;
var_name30 = 0;
var_name59 = checkIntInt(var_name30);
for( var_name554 = 8; var_name554 < 43; var_name554++ )
{   /* begin block block551 */
int var_name77;
var_name77 = 0;
int var_name209;
var_name209 = 0;
int var_name1095;
var_name1095 = 0;
var_name1095 = !(var_name77 == var_name209);
int var_name673;
var_name673 = 0;
var_name673 = !(firstarrayb[0] == var_name277);
char var_name528;
}   /* end block block551 */
int var_name673;
var_name673 = 0;
var_name673 = !(firstarrayb[0] == var_name277);
char var_name528;
}   /* end block block235 */
int var_name351;
var_name351 = 0;
/* Warn: Assign 4: curpos = 378, body = var_name239 var_name554 var_name351  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
float var_name1255[159];
/* Warn: Assign 3: curpos = 380, body = firstreal var_name493  */
/* Warn: Assign 3: type mismatch 1 & 2 = r & i */
firstreal = var_name493;
int var_name193;
var_name193 = 0;
while( var_name193 != 0 )
{   /* begin block block191 */
/* Warn: Assign 4: curpos = 383, body = var_name666 var_name817 var_name1107  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
int var_name455;
var_name455 = 0;
int var_name1009;
var_name1009 = 0;
int var_name1266;
var_name1266 = 0;
var_name1266 = !(var_name455 == var_name1009);
int var_name812;
var_name812 = 0;
printf(">%i<\n", var_name812);
int var_name698;
var_name698 = 0;
int var_name467;
var_name467 = 0;
int var_name753;
var_name753 = 0;
var_name753 = !(var_name698 == var_name467);
int var_name30;
var_name30 = 0;
 ++var_name30;
}   /* end block block191 */
char var_name731;
int var_name284;
var_name284 = 0;
int var_name1358;
var_name1358 = 0;
var_name1358 = !(var_name1052 == var_name284);
}   /* end block block295 */
int var_name445;
var_name445 = 0;
int var_name688;
var_name688 = 0;
var_name445 = var_name688;
int var_name351;
var_name351 = 0;
 ++var_name351;
int var_name30;
int var_name577;
var_name577 = 0;
int var_name1197;
var_name1197 = 0;
var_name475 = !(var_name577 == var_name1197);
int var_name720;
var_name720 = 0;
var_name577 = var_name637[var_name720];
int var_name1422;
var_name1422 = 0;
int var_name1018;
var_name1018 = 0;
int var_name1437;
var_name1437 = 0;
var_name1437 = !(var_name1422 == var_name1018);
int var_name1629;
var_name1629 = 0;
var_name1629 = checkIntInt(var_name95);
int var_name111;
var_name111 = 0;
int var_name623;
var_name623 = 0;
var_name623 = !(var_name596 == var_name111);
 ++var_name239;
{   /* begin block block998 */
{   /* begin block block134 */
int var_name1185;
var_name1185 = 0;
printf(">%i<\n", var_name1185);
int var_name1480;
var_name1480 = 0;
/* Warn: Assign 3: curpos = 406, body = firstchar var_name1480  */
/* Warn: Assign 3: type mismatch 1 & 2 = c & i */
firstchar = var_name1480;
}   /* end block block134 */
int var_name52;
var_name52 = 0;
var_name52 = checkIntBool(var_name69);
var_name95 = checkIntInt(var_name17);
int var_name640;
int var_name71;
var_name71 = 0;
int var_name13;
var_name13 = 0;
var_name71 = checkIntInt(var_name13);
int var_name1258;
var_name1258 = 0;
var_name1258 = 0;
int var_name1122;
var_name1122 = 0;
int var_name812;
var_name812 = 0;
var_name1122 = checkIntInt(var_name812);
 ++var_name17;
int var_name319;
var_name319 = 0;
var_name319 = checkIntBool(var_name69);
{   /* begin block block645 */
var_name225 = 0;
float var_name1251;
int var_name59;
var_name59 = 0;
firstboolean = !(var_name59 == var_name59);
int var_name1093;
var_name1093 = 0;
printf(">%i<\n", var_name1093);
printf(">%i<\n", firstint);
/* Warn: Assign 3: curpos = 421, body = var_name17 firstchar  */
/* Warn: Assign 3: type mismatch 1 & 2 = i & c */
var_name17 = firstchar;
}   /* end block block645 */
float var_name1251;
{   /* begin block block1727 */
int var_name59;
var_name59 = 0;
firstboolean = !(var_name59 == var_name59);
int var_name1093;
var_name1093 = 0;
printf(">%i<\n", var_name1093);
printf(">%i<\n", firstint);
for( var_name632 = 1; var_name632 > 1;var_name632-- )
{   /* begin block block629 */
/* Warn: Assign 3: curpos = 429, body = var_name17 firstchar  */
/* Warn: Assign 3: type mismatch 1 & 2 = i & c */
var_name17 = firstchar;
int var_name1800;
int var_name583;
var_name583 = 0;
var_name231 = checkIntInt(var_name583);
}   /* end block block629 */
int var_name1800;
int var_name583;
var_name583 = 0;
var_name231 = checkIntInt(var_name583);
int var_name571;
var_name571 = 0;
var_name571 = 0;
int var_name274;
var_name274 = 0;
int var_name540;
var_name540 = 0;
var_name540 = firstarrayb[var_name274];
printf(">%i<\n", var_name116);
var_name84 = 0;
int var_name287;
var_name287 = 0;
 ++var_name287;
int var_name311;
var_name311 = 0;
 ++var_name311;
int var_name1179;
var_name1179 = 0;
/* Warn: Assign 4: curpos = 441, body = var_name1093 var_name1179 firstreal  */
/* Warn: Assign 4: type mismatch 1 & 3 i & r */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
}   /* end block block1727 */
int var_name571;
var_name571 = 0;
var_name571 = 0;
int var_name274;
var_name274 = 0;
int var_name540;
var_name540 = 0;
var_name540 = firstarrayb[var_name274];
printf(">%i<\n", var_name116);
var_name84 = 0;
int var_name1179;
var_name1179 = 0;
for( var_name1179 = 18; var_name1179 < 55; var_name1179++ )
{   /* begin block block1176 */
int var_name287;
var_name287 = 0;
 ++var_name287;
int var_name393;
var_name393 = 0;
for( var_name393 = 4; var_name393 < 11; var_name393++ )
{   /* begin block block390 */
int var_name1163;
var_name1163 = 0;
while( var_name1163 != 0 )
{   /* begin block block1161 */
int var_name311;
var_name311 = 0;
 ++var_name311;
int var_name1093[DEFAULT_SIZE];
firstreal = var_name1093[var_name1179];
/* ........... adtq1_f 333 700  assign a idx elem   ........... */
int a[DEFAULT_SIZE];
int idx;
idx = 0;
int elem;
elem = 0;
elem = a[idx];
int var_name174;
var_name174 = 0;
/* Warn: Assign 4: curpos = 457, body = var_name666 var_name174 var_name1179  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
 ++var_name69;
}   /* end block block1161 */
}   /* end block block1176 */
int var_name311;
var_name311 = 0;
 ++var_name311;
int var_name1093[DEFAULT_SIZE];
firstreal = var_name1093[var_name1179];
}   /* end block block390 */
/* ........... adtq1_f 333 700  assign a idx elem   ........... */
int a[DEFAULT_SIZE];
int idx;
idx = 0;
int elem;
elem = 0;
elem = a[idx];
int var_name1863;
var_name1863 = 0;
while( var_name1863 != 0 )
{   /* begin block block1861 */
int var_name174;
var_name174 = 0;
/* Warn: Assign 4: curpos = 467, body = var_name666 var_name174 var_name1179  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
 ++var_name69;
int var_name887;
var_name887 = 0;
while( var_name887 != 0 )
{   /* begin block block922 */
int var_name223;
var_name223 = 0;
/* Warn: Assign 4: curpos = 471, body = var_name239 var_name223 var_name80  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
}   /* end block block922 */
{   /* begin block block847 */
{   /* begin block block1812 */
int var_name223;
var_name223 = 0;
/* Warn: Assign 4: curpos = 475, body = var_name239 var_name223 var_name80  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
}   /* end block block1812 */
}   /* end block block847 */
int var_name311;
var_name311 = 0;
for( var_name311 = 0; var_name311 > 9;var_name311-- )
{   /* begin block block308 */
int var_name223;
var_name223 = 0;
/* Warn: Assign 4: curpos = 480, body = var_name239 var_name223 var_name80  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
int var_name698;
int var_name403;
var_name403 = 0;
var_name21 = var_name591[var_name403];
}   /* end block block308 */
}   /* end block block1861 */
int var_name698;
int var_name403;
var_name403 = 0;
var_name21 = var_name591[var_name403];
}   /* end block block998 */
int var_name241[DEFAULT_SIZE];
int var_name13;
var_name13 = 0;
 ++var_name241[var_name13];
int var_name249;
var_name249 = 0;
var_name249 = checkIntInt(var_name493);
var_name84 = !(var_name116 == var_name95);
int var_name528;
var_name528 = 0;
int var_name707;
var_name707 = 0;
int var_name940;
var_name940 = 0;
var_name940 = !(var_name528 == var_name707);
int var_name1093[DEFAULT_SIZE];
var_name225 = var_name1093[var_name1107];
int var_name678;
var_name678 = 0;
if( var_name678 != 0 )
{   /* begin block if_then226 */
int var_name174;
var_name174 = 0;
/* Warn: Assign 4: curpos = 495, body = var_name149 var_name174 var_name30  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
}   /* end block if_then226 */
else {   /* begin ELSE block block676 */
int var_name71;
var_name71 = 0;
 ++var_name71;
}   /* end ELSE block block676 */
int var_name601;
var_name601 = 0;
 ++var_name601;
int var_name762;
var_name762 = 0;
for( var_name762 = 5; var_name762 < 13; var_name762++ )
{   /* begin block block759 */
int var_name71;
var_name71 = 0;
printf(">%i<\n", var_name71);
if( var_name367 != 0 )
{   /* begin block if_then227 */
var_name277 = 0;
int var_name48;
var_name48 = 0;
firstarrayb[var_name48] = 0;
}   /* end block if_then227 */
else {   /* begin ELSE block block1062 */
int var_name1319;
var_name1319 = 0;
var_name1319 = !(var_name686 == var_name988[0]);
}   /* end ELSE block block1062 */
}   /* end block block759 */
char var_name1692;
{   /* begin block block1090 */
int var_name403;
var_name403 = 0;
int var_name322;
var_name322 = 0;
int var_name440;
var_name440 = 0;
var_name440 = !(var_name403 == var_name322);
}   /* end block block1090 */
{   /* begin block block1574 */
int var_name223;
var_name223 = 0;
 ++var_name223;
 ++var_name1422;
printf(">%i<\n", var_name489);
printf(">%c<\n", firstarrayc[firstint]);
}   /* end block block1574 */
int var_name284;
var_name284 = 0;
var_name284 = checkIntInt(var_name249);
/* ........... adtq1_h 385 800  not_equals elem null result   ........... */
int elem;
elem = 0;
int result;
result = 0;
result = !(elem == null);
int var_name1002;
var_name1002 = 0;
printf(">%i<\n", var_name1002);
printf(">%i<\n", var_name239);
printf(">%i<\n", firstint);
int var_name451;
var_name451 = 0;
printf(">%i<\n", var_name451);
int var_name1556;
var_name1556 = 0;
for( var_name1556 = 59; var_name1556 > 63;var_name1556-- )
{   /* begin block block1553 */
printf(">%i<\n", var_name241[firstint]);
int var_name673;
var_name673 = 0;
int var_name1328;
var_name1328 = 0;
var_name673 = checkIntInt(var_name1328);
}   /* end block block1553 */
var_name131 = 0;
int var_name48;
int var_name1310[DEFAULT_SIZE];
int var_name1708;
var_name1708 = 0;
var_name1708 = var_name1310[var_name1197];
int var_name1328;
var_name1328 = 0;
for( var_name1328 = 0; var_name1328 > 0;var_name1328-- )
{   /* begin block block1325 */
}   /* end block block1325 */
var_name1107 = var_name1310[var_name1328];
char var_name812;
 ++var_name284;
int var_name403;
var_name403 = 0;
for( var_name403 = 3; var_name403 < 4; var_name403++ )
{   /* begin block block400 */
}   /* end block block400 */
var_name231 = firstarrayc[var_name403];
var_name21 = 0;
float var_name71;
int var_name554;
var_name554 = 0;
var_name637[0] = checkIntInt(var_name554);
int var_name393;
var_name393 = 0;
firstarrayr[0] = checkRealInt(var_name393);
{   /* begin block block1603 */
int var_name228;
var_name228 = 0;
int var_name467;
var_name467 = 0;
var_name467 = !(var_name228 == var_name69);
var_name601 = checkIntInt(var_name493);
int var_name1271;
var_name1271 = 0;
if( var_name1271 != 0 )
{   /* begin block if_then228 */
printf(">%i<\n", var_name513);
}   /* end block if_then228 */
else {   /* begin ELSE block block1269 */
int var_name322;
var_name30 = 0;
}   /* end ELSE block block1269 */
int var_name322;
var_name30 = 0;
}   /* end block block1603 */
printf(">%i<\n", var_name707);
int var_name461;
var_name461 = 0;
int var_name354;
var_name354 = 0;
int var_name1138;
var_name1138 = 0;
var_name1138 = !(var_name461 == var_name354);
{   /* begin block block663 */
int var_name99;
var_name99 = 0;
var_name99 = var_name116;
}   /* end block block663 */
while( var_name1629 != 0 )
{   /* begin block block1627 */
int var_name99;
var_name99 = 0;
int var_name193;
var_name193 = 0;
var_name193 = !(var_name95 == var_name99);
}   /* end block block1627 */
 ++var_name241[var_name1328];
int var_name322;
var_name322 = 0;
var_name343 = checkIntInt(var_name322);
char var_name1054;
var_name106 = checkIntInt(var_name67);
int var_name648;
var_name648 = 0;
int var_name77;
var_name77 = 0;
var_name648 = var_name77;
int var_name274;
var_name274 = 0;
for( var_name274 = 42; var_name274 > 73;var_name274-- )
{   /* begin block block271 */
}   /* end block block271 */
int var_name254;
var_name254 = 0;
/* Warn: Assign 4: curpos = 584, body = var_name239 var_name274 var_name254  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
int var_name1818;
var_name122 = checkIntInt(var_name343);
firstreal = 0.0;
 ++var_name623;
 ++firstarrayr[var_name7];
int var_name540;
var_name540 = 0;
var_name254 = !(var_name540 == var_name160);
int var_name563;
var_name563 = 0;
for( var_name563 = 42; var_name563 < 73; var_name563++ )
{   /* begin block block560 */
var_name231 = checkIntInt(var_name214);
int var_name52;
var_name52 = 0;
var_name52 = checkIntInt(var_name17);
var_name149 = checkIntInt(var_name48);
int var_name640;
var_name640 = 0;
var_name122 = var_name640;
int var_name1042;
var_name1042 = 0;
var_name1042 = var_name798;
}   /* end block block560 */
printf(">%i<\n", var_name277);
printf(">%i<\n", var_name563);
int var_name1495;
var_name1495 = 0;
for( var_name1495 = 98; var_name1495 < 100; var_name1495++ )
{   /* begin block block1492 */
int var_name836;
var_name836 = 0;
int var_name1075;
var_name1075 = 0;
/* Warn: Assign 4: curpos = 603, body = var_name666 var_name836 var_name1075  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
firstreal = checkRealInt(var_name17);
}   /* end block block1492 */
{   /* begin block block607 */
int var_name548;
var_name548 = 0;
 ++var_name548;
int var_name694;
var_name694 = 0;
 ++var_name591[var_name694];
for( var_name694 = 39; var_name694 < 42; var_name694++ )
{   /* begin block block691 */
int var_name611;
var_name611 = 0;
var_name241[0] = checkIntInt(var_name611);
int var_name704[DEFAULT_SIZE];
var_name704[var_name548] = 0;
char var_name1129[49];
}   /* end block block691 */
printf(">%i<\n", var_name277);
printf(">%i<\n", var_name694);
int var_name287;
var_name287 = 0;
var_name287 = !(var_name231 == var_name17);
int var_name258;
var_name258 = 0;
/* Warn: Assign 3: curpos = 617, body = var_name258 firstchar  */
/* Warn: Assign 3: type mismatch 1 & 2 = i & c */
var_name258 = firstchar;
int var_name228;
var_name228 = 0;
var_name228 = checkIntInt(var_name116);
{   /* begin block block1521 */
int var_name1600;
int var_name805[DEFAULT_SIZE];
int var_name1069;
var_name1069 = 0;
 ++var_name805[var_name1069];
var_name84 = !(var_name277 == firstarrayc[0]);
int var_name99;
var_name99 = 0;
var_name254 = !(var_name116 == var_name99);
int var_name1032;
var_name1032 = 0;
var_name1032 = var_name284;
int var_name1179;
var_name1179 = 0;
var_name1179 = checkIntInt(var_name491);
 ++var_name513;
}   /* end block block1521 */
int var_name805[DEFAULT_SIZE];
int var_name1069;
var_name1069 = 0;
 ++var_name805[var_name1069];
var_name84 = !(var_name277 == firstarrayc[0]);
int var_name99;
var_name99 = 0;
var_name254 = !(var_name116 == var_name99);
int var_name1032;
var_name1032 = 0;
var_name1032 = var_name284;
int var_name1179;
var_name1179 = 0;
var_name1179 = checkIntInt(var_name491);
 ++var_name513;
}   /* end block block607 */
var_name465 = firstarrayi[var_name445];
var_name239 = checkIntInt(var_name678);
int var_name1412;
var_name1412 = 0;
var_name1412 = var_name160;
int var_name174;
var_name174 = 0;
printf(">%i<\n", var_name174);
int var_name1028;
var_name1028 = 0;
var_name1028 = !(var_name554 == var_name465);
{   /* begin block block1460 */
var_name77 = !(var_name67 == var_name48);
int var_name1153;
printf(">%i<\n", var_name241[firstint]);
{   /* begin block block372 */
{   /* begin block block280 */
printf(">%i<\n", var_name277);
printf(">%i<\n", firstint);
int var_name805[DEFAULT_SIZE];
int var_name772;
var_name772 = 0;
int var_name455;
var_name455 = 0;
var_name455 = var_name805[var_name772];
firstint = checkIntChar(firstchar);
}   /* end block block280 */
}   /* end block block372 */
int var_name805[DEFAULT_SIZE];
int var_name772;
var_name772 = 0;
int var_name455;
var_name455 = 0;
var_name455 = var_name805[var_name772];
firstint = checkIntChar(firstchar);
}   /* end block block1460 */
int var_name59;
var_name59 = 0;
var_name59 = var_name1335;
int var_name52;
var_name52 = 0;
int var_name258;
var_name258 = 0;
var_name52 = checkIntInt(var_name258);
int var_name715;
var_name715 = 0;
int var_name1663;
var_name1663 = 0;
var_name1663 = !(var_name254 == var_name715);
int var_name1191;
var_name1191 = 0;
for( var_name1191 = 9; var_name1191 > 32;var_name1191-- )
{   /* begin block block1188 */
var_name80 = !(var_name30 == firstint);
firstarrayr[0] = checkRealInt(var_name30);
var_name116 = checkIntInt(var_name116);
int var_name209;
int var_name1789;
var_name1789 = 0;
var_name1789 = 0;
var_name17 = checkIntInt(var_name21);
{   /* begin block block1393 */
printf(">%c<\n", firstarrayc[var_name1191]);
}   /* end block block1393 */
printf(">%c<\n", firstarrayc[var_name1191]);
}   /* end block block1188 */
var_name7 = var_name7;
 ++var_name254;
var_name231 = 0;
firstreal = firstarrayr[var_name13];
int var_name640;
var_name640 = 0;
int var_name1534;
var_name1534 = 0;
/* Warn: Assign 4: curpos = 677, body = var_name1422 var_name640 var_name1534  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
int var_name1251;
var_name1251 = 0;
var_name817 = checkIntInt(var_name1251);
int var_name860;
var_name860 = 0;
while( var_name860 != 0 )
{   /* begin block block858 */
 ++firstarrayi[var_name30];
for( var_name1197 = 0; var_name1197 < 69; var_name1197++ )
{   /* begin block block1194 */
int var_name1185;
var_name1185 = 0;
var_name322 = checkIntInt(var_name1185);
}   /* end block block1194 */
}   /* end block block858 */
var_name540 = 0;
{   /* begin block block1124 */
int var_name287;
var_name287 = 0;
firstarrayi[0] = checkIntInt(var_name287);
int var_name865;
var_name865 = 0;
if( var_name865 != 0 )
{   /* begin block if_then229 */
float var_name1009;
char var_name1464;
}   /* end block if_then229 */
else {   /* begin ELSE block block1529 */
var_name71 = var_name591[var_name122];
int var_name99;
var_name99 = 0;
firstarrayi[0] = checkIntInt(var_name99);
int var_name681;
var_name681 = 0;
int var_name571;
var_name571 = 0;
var_name681 = checkIntInt(var_name571);
}   /* end ELSE block block1529 */
int var_name681;
var_name681 = 0;
int var_name571;
var_name571 = 0;
var_name681 = checkIntInt(var_name571);
}   /* end block block1124 */
int var_name852;
var_name852 = 0;
int var_name287;
var_name287 = 0;
int var_name1665;
var_name1665 = 0;
var_name1665 = !(var_name852 == var_name287);
int var_name745;
var_name745 = 0;
var_name59 = firstarrayr[var_name745];
int var_name1169;
var_name1169 = 0;
for( var_name1169 = 37; var_name1169 > 108;var_name1169-- )
{   /* begin block block337 */
{   /* begin block block1166 */
int var_name319;
printf(">%i<\n", var_name241[firstint]);
}   /* end block block1166 */
/* ........... adtq2_a 555 1100  decl array a2 char 99   ........... */
char a2[99];
int var_name1042;
var_name1042 = 0;
var_name1042 = 0;
firstarrayb[var_name179] = 0;
var_name601 = 0;
int var_name825;
var_name825 = 0;
var_name825 = checkIntChar(var_name812);
}   /* end block block337 */
 ++var_name239;
int var_name992[DEFAULT_SIZE];
int var_name845;
var_name845 = 0;
var_name845 = var_name992[var_name13];
var_name343 = 0;
int var_name1122;
var_name1122 = 0;
int var_name1478;
var_name1478 = 0;
var_name1122 = var_name1478;
{   /* begin block block262 */
int var_name1774;
var_name1774 = 0;
for( var_name1774 = 16; var_name1774 < 67; var_name1774++ )
{   /* begin block block1771 */
}   /* end block block1771 */
}   /* end block block262 */
int var_name1185;
var_name1185 = 0;
var_name1185 = 0;
int var_name938;
var_name938 = 0;
int var_name1687;
var_name1687 = 0;
var_name1687 = !(var_name77 == var_name938);
var_name149 = checkIntInt(var_name493);
int var_name42;
var_name42 = 0;
var_name116 = checkIntInt(var_name42);
int var_name1009;
var_name1009 = 0;
var_name1158 = !(var_name354 == var_name1009);
int var_name976;
var_name976 = 0;
var_name976 = var_name596;
int var_name1022;
var_name1022 = 0;
printf(">%i<\n", var_name1022);
int var_name548;
var_name548 = 0;
int var_name974;
var_name974 = 0;
var_name974 = var_name637[var_name548];
int var_name766;
var_name766 = 0;
var_name766 = var_name623;
int var_name850;
var_name850 = 0;
 ++var_name637[var_name850];
float var_name1203;
char var_name1209;
int var_name788;
var_name788 = 0;
int var_name1312;
var_name1312 = 0;
int var_name1798;
var_name1798 = 0;
var_name1798 = !(var_name788 == var_name1312);
int var_name611;
var_name611 = 0;
printf(">%i<\n", var_name611);
{   /* begin block block1695 */
int var_name887;
var_name887 = 0;
if( var_name887 != 0 )
{   /* begin block if_then230 */
int var_name482;
var_name482 = 0;
char var_name176;
var_name176 = 0;
var_name176 = firstarrayc[var_name482];
}   /* end block if_then230 */
else {   /* begin ELSE block block885 */
{   /* begin block block1224 */
}   /* end block block1224 */
int var_name694;
var_name694 = 0;
var_name694 = checkIntReal(* var_name591);
int var_name704;
var_name704 = 0;
var_name1482 = checkIntInt(var_name704);
int var_name176;
var_name176 = 0;
var_name176 = checkIntInt(var_name354);
}   /* end ELSE block block885 */
}   /* end block block1695 */
printf(">%i<\n", var_name284);
var_name284 = checkIntInt(var_name239);
/* Warn I2: Increment bad type : curpos =757, body = firstarrayc firstint  */
 ++firstarrayc[0];
int var_name815;
var_name815 = 0;
/* Warn: Assign 4: curpos = 758, body = var_name239 var_name815 var_name214  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
 ++var_name149;
int var_name1778[DEFAULT_SIZE];
int var_name1349;
var_name1349 = 0;
var_name707 = var_name1778[var_name1349];
printf(">%i<\n", var_name17);
var_name1136 = !(var_name1122 == var_name95);
/* ........... adtq2_b 606 1200  zero idx2   ........... */
int idx2;
idx2 = 0;
idx2 = 0;
int var_name176;
var_name176 = 0;
 ++var_name176;
{   /* begin block block385 */
 ++var_name1169;
{   /* begin block block137 */
int var_name681;
var_name681 = 0;
 ++var_name681;
char var_name99;
var_name239 = checkIntInt(var_name17);
var_name214 = checkIntInt(var_name145);
int var_name504;
var_name504 = 0;
var_name1093[0] = checkIntInt(var_name504);
var_name67 = checkIntReal(* firstarrayr);
}   /* end block block137 */
var_name239 = checkIntInt(var_name17);
var_name214 = checkIntInt(var_name145);
int var_name504;
var_name504 = 0;
var_name1093[0] = checkIntInt(var_name504);
var_name67 = checkIntReal(* firstarrayr);
}   /* end block block385 */
int var_name772;
var_name772 = 0;
/* Warn: Assign 4: curpos = 783, body = var_name1018 var_name772 var_name540  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
var_name403 = checkIntInt(var_name577);
 ++var_name287;
var_name179 = var_name13;
int var_name1374;
int var_name1111[DEFAULT_SIZE];
int var_name694;
var_name694 = 0;
var_name1122 = var_name1111[var_name694];
var_name258 = 0;
firstarrayb[0] = checkBoolChar(var_name1054);
firstint = firstarrayi[firstint];
var_name225 = checkIntInt(var_name601);
{   /* begin block block155 */
var_name225 = checkIntInt(var_name563);
var_name17 = checkIntInt(* firstarrayi);
firstarrayb[0] = checkBoolInt(var_name528);
{   /* begin block block469 */
int var_name945;
var_name945 = 0;
var_name1251 = checkIntInt(var_name945);
int var_name319;
var_name319 = 0;
int var_name99;
var_name99 = 0;
var_name319 = checkIntInt(var_name99);
{   /* begin block block1408 */
var_name59 = checkIntInt(var_name7);
int var_name605;
var_name605 = 0;
int var_name455;
var_name455 = 0;
var_name623 = !(var_name605 == var_name455);
var_name48 = checkIntInt(var_name772);
int var_name482;
var_name482 = 0;
for( var_name482 = 7; var_name482 < 11; var_name482++ )
{   /* begin block block479 */
var_name158 = checkIntInt(var_name84);
 ++var_name277;
int var_name805[DEFAULT_SIZE];
int var_name621;
var_name621 = 0;
var_name805[var_name621] = 0;
var_name158 = checkIntInt(var_name84);
}   /* end block block479 */
}   /* end block block1408 */
 ++var_name277;
}   /* end block block469 */
int var_name805[DEFAULT_SIZE];
int var_name621;
var_name621 = 0;
var_name805[var_name621] = 0;
}   /* end block block155 */
int var_name109;
var_name109 = 0;
int var_name193;
var_name193 = 0;
var_name193 = !(var_name109 == var_name109);
var_name988[var_name1495] = 0;
/* ........... adtq2_c 657 1300  while result2   ........... */
int result2;
result2 = 0;
if( result2 != 0 )
{   /* begin block if_then231 */
char var_name99;
var_name99 = 0;
var_name99 = firstarrayc[var_name322];
firstarrayr[0] = checkRealChar(var_name99);
int var_name955;
var_name955 = 0;
printf(">%i<\n", var_name955);
int var_name223;
var_name223 = 0;
var_name223 = checkIntInt(var_name131);
var_name13 = checkIntInt(var_name30);
}   /* end block if_then231 */
/* ........... adtq2_d 663 1310  elsebegin block2   ........... */
else {   /* begin ELSE block block2 */
while( var_name249 != 0 )
{   /* begin block block1213 */
int var_name223;
var_name223 = 0;
var_name223 = checkIntInt(var_name678);
}   /* end block block1213 */
var_name225 = var_name591[var_name632];
printf(">%i<\n", var_name601);
var_name720 = var_name745;
var_name176 = 0;
int var_name99;
var_name99 = 0;
var_name99 = var_name491;
int var_name440;
var_name440 = 0;
int var_name700;
var_name700 = 0;
int var_name1287;
var_name1287 = 0;
var_name1287 = !(var_name440 == var_name700);
int var_name1261;
var_name1261 = 0;
while( var_name1261 != 0 )
{   /* begin block block1367 */
char var_name1032;
}   /* end block block1367 */
var_name766 = !(var_name489 == var_name322);
{   /* begin block block1580 */
int var_name1255[DEFAULT_SIZE];
 ++var_name1255[var_name694];
int var_name1561;
var_name1561 = 0;
/* Warn: Assign 4: curpos = 850, body = var_name666 var_name1719 var_name1561  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
{   /* begin block block1377 */
}   /* end block block1377 */
}   /* end block block1580 */
while( var_name540 != 0 )
{   /* begin block block659 */
float var_name455;
printf(">%i<\n", var_name30);
var_name71 = checkRealInt(var_name95);
int var_name1271;
var_name1271 = 0;
int var_name1676;
var_name1676 = 0;
var_name1271 = checkIntInt(var_name1676);
}   /* end block block659 */
{   /* begin block block1370 */
/* Warn: Assign 4: curpos = 864, body = var_name239 var_name274 var_name84  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
firstarrayr[var_name131] = 0.0;
/* ........... adtq2_g 699 1400  assign a2 idx2 elemb2   ........... */
int a2[DEFAULT_SIZE];
int elemb2;
elemb2 = 0;
elemb2 = a2[idx2];
firstarrayi[0] = checkIntInt(var_name145);
var_name71 = checkRealReal(* firstarrayr);
{   /* begin block block1240 */
int var_name731;
var_name731 = 0;
var_name686 = checkIntInt(var_name731);
var_name176 = var_name145;
printf(">%i<\n", var_name149);
printf(">%i<\n", firstint);
var_name513 = var_name21;
int var_name204;
var_name204 = 0;
var_name106 = var_name204;
 ++var_name21;
}   /* end block block1240 */
var_name176 = var_name145;
printf(">%i<\n", var_name149);
printf(">%i<\n", firstint);
var_name513 = var_name21;
int var_name204;
var_name204 = 0;
var_name106 = var_name204;
int var_name1646;
var_name1646 = 0;
for( var_name1646 = 4; var_name1646 > 13;var_name1646-- )
{   /* begin block block1643 */
 ++var_name21;
}   /* end block block1643 */
}   /* end block block1370 */
int var_name731;
var_name731 = 0;
var_name731 = 0;
/* Warn: Assign 4: curpos = 890, body = var_name666 var_name67 var_name131  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
printf(">%i<\n", var_name277);
printf(">%i<\n", firstint);
int var_name212;
var_name212 = 0;
while( var_name212 != 0 )
{   /* begin block block316 */
}   /* end block block316 */
int var_name1748[138];
/* Warn: Assign 3: curpos = 897, body = firstreal var_name513  */
/* Warn: Assign 3: type mismatch 1 & 2 = r & i */
firstreal = var_name513;
while( var_name77 != 0 )
{   /* begin block block75 */
while( var_name351 != 0 )
{   /* begin block block349 */
var_name131 = checkIntInt(var_name212);
}   /* end block block349 */
var_name131 = checkIntInt(var_name212);
}   /* end block block75 */
{   /* begin block block556 */
/* Warn: Assign 4: curpos = 907, body = var_name277 var_name106 var_name176  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
}   /* end block block556 */
int var_name1383;
var_name1469[0] = checkIntInt(var_name1009);
var_name596 = !(var_name817 == var_name274);
float var_name1796;
while( var_name938 != 0 )
{   /* begin block block1525 */
int var_name1363;
var_name1363 = 0;
while( var_name1363 != 0 )
{   /* begin block block1361 */
/* ........... adtq2_i 743 1500  increment idx2   ........... */
 ++idx2;
int var_name1134;
}   /* end block block1361 */
}   /* end block block1525 */
var_name99 = var_name176;
{   /* begin block block27 */
int var_name836;
var_name836 = 0;
var_name611 = checkIntInt(var_name836);
{   /* begin block block369 */
 ++var_name343;
printf(">%i<\n", var_name637[firstint]);
}   /* end block block369 */
 ++var_name343;
printf(">%i<\n", var_name637[firstint]);
}   /* end block block27 */
var_name461 = firstarrayr[var_name548];
/* Warn: Assign 3: curpos = 933, body = var_name109 firstreal  */
/* Warn: Assign 3: type mismatch 1 & 2 = i & r */
var_name109 = firstreal;
 ++var_name731;
 ++var_name17;
firstarrayb[0] = checkBoolInt(var_name17);
printf(">%4.2f<\n", firstarrayr[firstint]);
int var_name1075;
var_name1075 = 0;
var_name1075 = checkIntInt(var_name788);
int var_name1129[DEFAULT_SIZE];
firstchar = var_name1129[var_name563];
int var_name704[144];
float var_name1776;
var_name109 = var_name513;
{   /* begin block block642 */
int var_name805[DEFAULT_SIZE];
 ++var_name805[var_name577];
{   /* begin block block566 */
int var_name209;
var_name209 = 0;
var_name209 = !(var_name116 == firstchar);
}   /* end block block566 */
int var_name209;
var_name209 = 0;
var_name209 = !(var_name116 == firstchar);
}   /* end block block642 */
int var_name482;
var_name482 = 0;
var_name48 = var_name637[var_name482];
int var_name223;
var_name223 = 0;
var_name274 = var_name223;
var_name52 = var_name1251;
char var_name1761;
{   /* begin block block1263 */
for( var_name788 = 20; var_name788 > 83;var_name788-- )
{   /* begin block block785 */
var_name491 = checkIntInt(var_name158);
}   /* end block block785 */
}   /* end block block1263 */
var_name678 = var_name540;
/* ........... adtq2_e 785 1600  elseend block2   ........... */
}   /* end ELSE block block2 */
int var_name945;
var_name945 = 0;
var_name17 = checkIntInt(var_name945);
int var_name455;
var_name455 = 0;
var_name122 = checkIntInt(var_name455);
int var_name626;
var_name626 = 0;
int var_name751;
var_name751 = 0;
var_name626 = var_name751;
int var_name212;
var_name212 = 0;
var_name212 = !(var_name241[0] == var_name241[0]);
{   /* begin block block1354 */
int var_name704;
var_name704 = 0;
printf(">%i<\n", var_name704);
printf(">%i<\n", firstint);
printf(">%i<\n", var_name149);
printf(">%i<\n", firstint);
/* Warn: Assign 4: curpos = 970, body = var_name239 var_name815 var_name367  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
var_name493 = checkIntInt(var_name403);
int var_name621;
var_name621 = 0;
for( var_name621 = 6; var_name621 < 31; var_name621++ )
{   /* begin block block618 */
/* Warn: Assign 4: curpos = 975, body = var_name149 var_name67 var_name274  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
while( var_name214 != 0 )
{   /* begin block block429 */
}   /* end block block618 */
var_name611 = var_name59;
}   /* end block block429 */
}   /* end block block1354 */
for( var_name751 = 3; var_name751 > 67;var_name751-- )
{   /* begin block block748 */
var_name214 = !(firstchar == var_name95);
while( var_name715 != 0 )
{   /* begin block block879 */
while( firstboolean != 0 )
{   /* begin block block56 */
int var_name328;
var_name328 = 0;
while( var_name328 != 0 )
{   /* begin block block326 */
int var_name406;
var_name406 = 0;
var_name406 = !(var_name491 == var_name491);
printf(">%i<\n", var_name686);
printf(">%i<\n", var_name751);
}   /* end block block326 */
}   /* end block block56 */
printf(">%i<\n", var_name686);
printf(">%i<\n", var_name751);
}   /* end block block879 */
}   /* end block block748 */
printf(">%i<\n", firstarrayi[firstint]);
int var_name1870;
var_name1870 = 0;
for( var_name1870 = 35; var_name1870 > 116;var_name1870-- )
{   /* begin block block1867 */
{   /* begin block block245 */
int var_name375;
var_name375 = 0;
 ++var_name375;
var_name176 = checkIntReal(* firstarrayr);
var_name52 = checkIntInt(var_name116);
char var_name1258;
}   /* end block block245 */
char var_name1258;
}   /* end block block1867 */
int var_name1789;
var_name1789 = 0;
var_name1789 = var_name109;
 ++var_name241[var_name174];
int var_name807;
int var_name1065;
var_name1065 = 0;
/* Warn: Assign 3: curpos = 1013, body = var_name69 var_name1065  */
/* Warn: Assign 3: type mismatch 1 & 2 = b & i */
var_name69 = var_name1065;
printf(">%i<\n", var_name343);
printf(">%i<\n", firstint);
printf(">%i<\n", var_name274);
{   /* begin block block195 */
var_name13 = firstarrayi[var_name30];
/* ........... adtq2_f 839 1700  assign a2 idx2 elem2   ........... */
int a2[DEFAULT_SIZE];
int elem2;
elem2 = 0;
elem2 = a2[idx2];
}   /* end block block195 */
var_name287 = checkIntInt(var_name772);
int var_name704[DEFAULT_SIZE];
int var_name962;
var_name962 = 0;
var_name751 = var_name704[var_name962];
printf(">%4.2f<\n", firstarrayr[firstint]);
int var_name228;
var_name228 = 0;
var_name228 = checkIntInt(var_name225);
/* Warn: Assign 3: curpos = 1025, body = var_name17 firstchar  */
/* Warn: Assign 3: type mismatch 1 & 2 = i & c */
var_name17 = firstchar;
for( var_name489 = 6; var_name489 < 50; var_name489++ )
{   /* begin block block486 */
 ++firstarrayi[var_name179];
int var_name361;
var_name361 = 0;
var_name751 = var_name361;
}   /* end block block486 */
printf(">%c<\n", firstarrayc[var_name489]);
int var_name593;
var_name593 = 0;
var_name593 = !(firstreal == var_name21);
int var_name865;
var_name865 = 0;
while( var_name865 != 1 )
{   /* begin block blockfix232 */
while( var_name436 != 0 )
{   /* begin block block434 */
{   /* begin block block863 */
}   /* end block block863 */
}   /* end block block434 */
}   /* end block blockfix232 */
{   /* begin block block854 */
int var_name1509;
int var_name223;
var_name223 = 0;
var_name17 = firstarrayc[var_name223];
firstboolean = !(var_name277 == var_name686);
var_name343 = checkIntInt(var_name611);
int var_name425;
var_name425 = 0;
var_name106 = var_name425;
var_name21 = checkIntInt(var_name59);
int var_name621;
var_name621 = 0;
var_name116 = var_name241[var_name621];
}   /* end block block854 */
int var_name830;
{   /* begin block block1635 */
var_name284 = checkIntInt(var_name611);
int var_name1480;
var_name1480 = 0;
var_name1482 = !(var_name1209 == var_name1480);
int var_name311;
var_name311 = 0;
/* Warn I2: Increment bad type : curpos =1055, body = firstarrayc var_name311  */
 ++firstarrayc[0];
int var_name1101;
var_name1101 = 0;
for( var_name1101 = 9; var_name1101 < 14; var_name1101++ )
{   /* begin block block1098 */
printf(">%i<\n", firstarrayb[firstint]);
}   /* end block block1098 */
 ++firstarrayr[var_name850];
}   /* end block block1635 */
var_name1467 = checkBoolReal(var_name1203);
int var_name1266;
var_name1266 = 0;
var_name1266 = !(var_name1145 == var_name817);
int var_name825;
var_name825 = 0;
var_name455 = checkIntInt(var_name825);
var_name601 = checkIntInt(* firstarrayi);
/* ........... adtq2_h 886 1800  not_equals elem2 null result2   ........... */
int elem2;
elem2 = 0;
result2 = !(elem2 == null);
firstarrayi[0] = checkIntInt(var_name258);
int var_name1698;
var_name1698 = 0;
var_name1698 = var_name231;
printf(">%i<\n", var_name277);
printf(">%i<\n", firstint);
{   /* begin block block1385 */
{   /* begin block block1824 */
firstint = firstint;
}   /* end block block1824 */
}   /* end block block1385 */
for( var_name772 = 72; var_name772 < 144; var_name772++ )
{   /* begin block block769 */
var_name13 = checkIntInt(* var_name241);
}   /* end block block769 */
int var_name681;
var_name681 = 0;
var_name95 = var_name681;
int var_name425;
var_name425 = 0;
for( var_name425 = 44; var_name425 > 71;var_name425-- )
{   /* begin block block422 */
var_name160 = checkIntInt(var_name149);
}   /* end block block422 */
/* Warn: Assign 4: curpos = 1086, body = var_name239 var_name425 var_name212  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
{   /* begin block block1542 */
var_name241[0] = checkIntInt(var_name284);
 ++var_name277;
int var_name1721;
var_name1721 = 0;
printf(">%i<\n", var_name1721);
printf(">%i<\n", firstint);
int var_name1163;
var_name1163 = 0;
int var_name1258;
var_name1258 = 0;
var_name1163 = checkIntInt(var_name1258);
}   /* end block block1542 */
{   /* begin block block1548 */
char var_name519;
int var_name1401;
var_name1401 = 0;
while( var_name1401 != 0 )
{   /* begin block block1399 */
}   /* end block block1399 */
}   /* end block block1548 */
var_name158 = checkIntInt(firstboolean);
int var_name836;
var_name836 = 0;
var_name48 = var_name836;
printf(">%i<\n", var_name1310[firstint]);
var_name812 = checkCharReal(* firstarrayr);
var_name225 = checkIntInt(var_name145);
var_name807 = checkBoolInt(var_name528);
firstreal = checkRealInt(var_name21);
var_name258 = firstarrayc[var_name131];
for( var_name106 = 8; var_name106 < 29; var_name106++ )
{   /* begin block block103 */
}   /* end block block103 */
printf(">%c<\n", firstarrayc[var_name106]);
int var_name1785;
var_name1785 = 0;
for( var_name1785 = 12; var_name1785 > 27;var_name1785-- )
{   /* begin block block1782 */
int var_name1591;
var_name1591 = 0;
for( var_name1591 = 0; var_name1591 < 85; var_name1591++ )
{   /* begin block block1588 */
int var_name1506;
var_name1506 = 0;
for( var_name1506 = 25; var_name1506 > 61;var_name1506-- )
{   /* begin block block1503 */
}   /* end block block1503 */
var_name145 = 0;
var_name601 = checkIntInt(var_name1002);
}   /* end block block1588 */
int var_name99;
var_name99 = 0;
var_name99 = 0;
var_name637[0] = checkIntInt(var_name131);
printf(">%c<\n", firstarrayc[firstint]);
}   /* end block block1782 */
var_name1028 = !(var_name287 == var_name42);
var_name563 = var_name67;
var_name812 = 0;
int var_name1343;
var_name1343 = 0;
for( var_name1343 = 8; var_name1343 < 20; var_name1343++ )
{   /* begin block block1340 */
}   /* end block block1340 */
int var_name223;
var_name223 = 0;
var_name976 = !(var_name850 == var_name223);
printf(">%i<\n", var_name239);
printf(">%i<\n", var_name1343);
int var_name1458;
var_name1458 = 0;
for( var_name1458 = 4; var_name1458 < 24; var_name1458++ )
{   /* begin block block1455 */
var_name80 = checkIntReal(firstreal);
 ++var_name71;
}   /* end block block1455 */
var_name976 = firstarrayb[var_name1458];
int var_name519;
var_name519 = 0;
int var_name406;
var_name406 = 0;
var_name519 = checkIntInt(var_name406);
{   /* begin block block1845 */
int var_name204;
var_name204 = 0;
for( var_name204 = 8; var_name204 < 12; var_name204++ )
{   /* begin block block201 */
}   /* end block block201 */
{   /* begin block block167 */
var_name7 = 0;
int var_name99;
var_name99 = 0;
var_name99 = var_name95;
int var_name605;
var_name605 = 0;
int var_name801;
var_name801 = 0;
var_name852 = !(var_name605 == var_name801);
printf(">%i<\n", var_name1018);
printf(">%i<\n", firstint);
int var_name1303;
var_name1303 = 0;
var_name1303 = !(var_name231 == var_name681);
}   /* end block block167 */
int var_name99;
var_name99 = 0;
var_name99 = var_name95;
int var_name605;
var_name605 = 0;
int var_name801;
var_name801 = 0;
var_name852 = !(var_name605 == var_name801);
{   /* begin block block506 */
printf(">%i<\n", var_name1018);
printf(">%i<\n", firstint);
int var_name1303;
var_name1303 = 0;
var_name1303 = !(var_name231 == var_name681);
}   /* end block block506 */
}   /* end block block1845 */
 ++var_name591[var_name131];
int var_name467;
var_name467 = 0;
var_name467 = !(var_name212 == var_name351);
int var_name571;
var_name571 = 0;
 ++var_name571;
var_name106 = var_name106;
var_name214 = !(var_name274 == var_name67);
firstboolean = firstarrayb[firstint];
printf(">%c<\n", firstarrayc[firstint]);
int var_name753;
var_name753 = 0;
var_name753 = firstarrayb[var_name720];
 ++var_name611;
int var_name99;
var_name99 = 0;
 ++var_name99;
{   /* begin block block1428 */
int var_name1740;
{   /* begin block block152 */
var_name406 = !(var_name109 == var_name59);
float var_name1536[190];
var_name751 = 0;
var_name528 = checkIntInt(var_name611);
var_name715 = !(var_name491 == var_name707);
int var_name375;
var_name375 = 0;
var_name111 = !(var_name30 == var_name375);
}   /* end block block152 */
var_name751 = 0;
var_name528 = checkIntInt(var_name611);
var_name715 = !(var_name491 == var_name707);
for( var_name836 = 41; var_name836 > 44;var_name836-- )
{   /* begin block block833 */
int var_name375;
var_name375 = 0;
var_name111 = !(var_name30 == var_name375);
}   /* end block block833 */
}   /* end block block1428 */
var_name149 = 0;
int var_name1615;
var_name1615 = 0;
if( var_name1615 != 0 )
{   /* begin block if_then233 */
printf(">%i<\n", var_name996[firstint]);
}   /* end block if_then233 */
else {   /* begin ELSE block block1613 */
firstarrayi[0] = checkIntInt(var_name254);
int var_name605;
var_name605 = 0;
var_name605 = var_name225;
{   /* begin block block1743 */
printf(">%4.2f<\n", var_name71);
int var_name1255;
var_name1255 = 0;
printf(">%i<\n", var_name1255);
printf(">%i<\n", firstint);
int var_name1595;
var_name1595 = 0;
var_name1595 = !(var_name601 == var_name99);
int var_name1734;
var_name1734 = 0;
int var_name1737;
var_name1737 = 0;
var_name1737 = !(var_name845 == var_name1734);
}   /* end block block1743 */
int var_name1734;
var_name1734 = 0;
int var_name1737;
var_name1737 = 0;
var_name1737 = !(var_name845 == var_name1734);
}   /* end ELSE block block1613 */
float var_name1713;
int var_name1593;
var_name1593 = 0;
var_name1593 = !(var_name1458 == var_name1349);
var_name640 = checkIntInt(var_name528);
while( var_name80 != 0 )
{   /* begin block block163 */
char var_name1489;
var_name174 = checkIntInt(var_name106);
}   /* end block block163 */
 ++var_name519;
var_name176 = checkIntReal(firstreal);
char var_name1052;
var_name179 = checkIntInt(* var_name241);
int var_name1487;
var_name1487 = 0;
var_name1487 = !(var_name513 == var_name109);
 ++var_name1111[var_name912];
printf(">%i<\n", var_name239);
printf(">%i<\n", firstint);
var_name145 = checkIntInt(var_name239);
{   /* begin block block931 */
}   /* end block block931 */
for( var_name1107 = 12; var_name1107 > 16;var_name1107-- )
{   /* begin block block1104 */
var_name241[0] = checkIntInt(var_name601);
var_name571 = checkIntInt(var_name179);
var_name591[var_name548] = 0.0;
printf(">%i<\n", var_name455);
}   /* end block block1104 */
var_name95 = 0;
int var_name328;
var_name328 = 0;
var_name328 = var_name451;
var_name149 = checkIntInt(var_name461);
int var_name1163;
var_name1163 = 0;
if( var_name1163 != 0 )
{   /* begin block if_then234 */
var_name491 = checkIntInt(var_name648);
}   /* end block if_then234 */
else {   /* begin ELSE block block1432 */
var_name455 = firstarrayr[var_name322];
int var_name1853;
var_name1853 = 0;
for( var_name1853 = 1; var_name1853 > 1;var_name1853-- )
{   /* begin block block1850 */
printf(">%i<\n", var_name241[firstint]);
}   /* end block block1850 */
printf(">%i<\n", var_name241[firstint]);
int var_name1516;
var_name1516 = 0;
while( var_name1516 != 0 )
{   /* begin block block1514 */
float var_name605;
}   /* end block block1514 */
float var_name605;
}   /* end ELSE block block1432 */
int var_name947[91];
var_name815 = firstarrayi[var_name554];
var_name367 = var_name1163;
int var_name1545;
int var_name1117;
var_name1117 = 0;
int var_name1134;
var_name1134 = 0;
var_name1117 = var_name1134;
printf(">%i<\n", firstarrayi[firstint]);
 ++var_name225;
firstchar = checkCharReal(firstreal);
var_name145 = checkIntInt(var_name455);
{   /* begin block block1658 */
/* Warn: Assign 3: curpos = 1273, body = var_name59 var_name1203  */
/* Warn: Assign 3: type mismatch 1 & 2 = i & r */
var_name59 = var_name1203;
int var_name1721[177];
int var_name673;
}   /* end block block1658 */
var_name751 = 0;
 ++var_name996[var_name122];
printf(">%i<\n", firstarrayi[firstint]);
var_name258 = checkIntReal(* firstarrayr);
float var_name1776;
var_name1776 = 0;
var_name1776 = var_name1668[var_name836];
var_name42 = checkIntReal(* firstarrayr);
while( var_name1117 != 0 )
{   /* begin block block1115 */
}   /* end block block1115 */
int var_name621;
var_name621 = 0;
int var_name1768;
var_name1768 = 0;
var_name1768 = !(var_name1197 == var_name621);
int var_name311;
var_name311 = 0;
var_name311 = checkIntInt(var_name406);
var_name621 = var_name106;
var_name214 = !(var_name95 == var_name95);
int var_name1740;
var_name1740 = 0;
/* Warn I2: Increment bad type : curpos =1292, body = firstarrayc var_name1740  */
 ++firstarrayc[0];
{   /* begin block block206 */
var_name84 = !(var_name30 == var_name7);
while( firstboolean != 0 )
{   /* begin block block35 */
printf(">%c<\n", firstarrayc[firstint]);
int var_name1787[DEFAULT_SIZE];
 ++var_name1787[var_name1458];
var_name1719 = checkIntInt(var_name95);
var_name228 = !(var_name214 == var_name111);
var_name71 = firstarrayr[var_name106];
}   /* end block block35 */
{   /* begin block block1300 */
var_name992[0] = checkIntInt(var_name122);
 ++var_name131;
var_name42 = !(var_name17 == var_name17);
var_name145 = checkIntInt(var_name131);
int var_name1069;
var_name1069 = 0;
var_name694 = firstarrayi[var_name1069];
int var_name1518;
 ++var_name174;
}   /* end block block1300 */
 ++var_name131;
var_name42 = !(var_name17 == var_name17);
var_name145 = checkIntInt(var_name131);
int var_name1069;
var_name1069 = 0;
var_name694 = firstarrayi[var_name1069];
{   /* begin block block171 */
for( var_name974 = 15; var_name974 > 23;var_name974-- )
{   /* begin block block971 */
int var_name1518;
 ++var_name174;
var_name122 = checkIntInt(var_name707);
}   /* end block block971 */
var_name122 = checkIntInt(var_name707);
}   /* end block block171 */
}   /* end block block206 */
var_name145 = var_name95;
printf(">%c<\n", firstarrayc[firstint]);
var_name328 = firstarrayb[var_name788];
int var_name1358;
var_name1358 = 0;
/* Warn: Assign 4: curpos = 1330, body = var_name1018 var_name815 var_name1358  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
var_name704[var_name425] = 0;
/* Warn: Assign 4: curpos = 1332, body = var_name239 var_name223 var_name84  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
while( var_name678 != 0 )
{   /* begin block block1235 */
int var_name1220;
int var_name1075;
var_name1075 = 0;
var_name436 = checkIntInt(var_name1075);
var_name912 = var_name122;
}   /* end block block1235 */
int var_name955;
var_name955 = 0;
for( var_name955 = 1; var_name955 < 2; var_name955++ )
{   /* begin block block952 */
}   /* end block block952 */
var_name455 = var_name591[var_name955];
float var_name1499;
 ++var_name174;
{   /* begin block block1147 */
var_name287 = !(firstreal == var_name52);
int var_name731;
var_name731 = 0;
printf(">%i<\n", var_name731);
int var_name583;
var_name583 = 0;
firstchar = checkCharInt(var_name583);
var_name160 = !(firstarrayi[0] == firstarrayr[0]);
}   /* end block block1147 */
var_name1122 = 0;
var_name436 = checkIntInt(var_name354);
while( var_name287 != 0 )
{   /* begin block block985 */
}   /* end block block985 */
{   /* begin block block935 */
}   /* end block block935 */
for( var_name122 = 27; var_name122 < 48; var_name122++ )
{   /* begin block block119 */
float var_name801;
for( var_name13 = 7; var_name13 > 14;var_name13-- )
{   /* begin block block10 */
}   /* end block block10 */
var_name13 = firstarrayi[var_name13];
}   /* end block block119 */
var_name52 = firstarrayr[var_name122];
int var_name805;
var_name805 = 0;
int var_name700;
var_name700 = 0;
var_name700 = !(var_name805 == var_name1018);
int var_name204;
var_name204 = 0;
 ++var_name704[var_name204];
int var_name583;
var_name583 = 0;
var_name591[0] = checkRealInt(var_name583);
var_name99 = checkIntInt(var_name393);
 ++var_name241[var_name158];
var_name30 = var_name122;
int var_name1081;
var_name1081 = 0;
for( var_name1081 = 12; var_name1081 < 25; var_name1081++ )
{   /* begin block block1078 */
for( var_name223 = 17; var_name223 < 35; var_name223++ )
{   /* begin block block220 */
}   /* end block block220 */
var_name111 = firstarrayb[var_name223];
}   /* end block block1078 */
/* Warn I2: Increment bad type : curpos =1382, body = var_name812  */
var_name812 = ++var_name812;
var_name69 = !(var_name69 == var_name77);
var_name1022 = checkIntInt(var_name491);
var_name231 = checkIntInt(var_name30);
int var_name504;
var_name504 = 0;
var_name504 = !(var_name274 == var_name179);
int var_name1032;
var_name1032 = 0;
var_name1032 = 0;
/* Warn: Assign 4: curpos = 1388, body = var_name239 var_name174 var_name715  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
int var_name1561;
for( var_name577 = 5; var_name577 > 12;var_name577-- )
{   /* begin block block574 */
var_name67 = 0;
/* Warn: Assign 3: curpos = 1393, body = var_name528 firstchar  */
/* Warn: Assign 3: type mismatch 1 & 2 = i & c */
var_name528 = firstchar;
/* Warn: Assign 4: curpos = 1394, body = var_name343 var_name311 var_name176  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
int var_name1151;
var_name1151 = 0;
 ++var_name1151;
}   /* end block block574 */
 ++firstarrayb[var_name7];
{   /* begin block block1757 */
 ++firstarrayi[var_name7];
var_name593 = checkIntInt(var_name1169);
var_name845 = var_name681;
firstchar = 0;
firstint = checkIntInt(var_name258);
int var_name361;
var_name361 = 0;
var_name361 = checkIntInt(var_name455);
int var_name1075;
var_name1075 = 0;
for( var_name1075 = 29; var_name1075 < 38; var_name1075++ )
{   /* begin block block1072 */
}   /* end block block1072 */
}   /* end block block1757 */
var_name493 = var_name493;
var_name249 = 0;
int var_name605;
var_name605 = 0;
var_name605 = 0;
{   /* begin block block964 */
var_name69 = !(var_name249 == var_name249);
}   /* end block block964 */
 ++var_name491;
/* Warn: Assign 4: curpos = 1420, body = var_name239 var_name621 var_name623  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
var_name637[var_name67] = 0;
var_name231 = 0;
var_name42 = !(firstboolean == firstboolean);
int var_name1705;
var_name1705 = 0;
var_name1163 = var_name1705;
firstarrayb[0] = checkBoolInt(var_name445);
int var_name1577;
var_name1577 = 0;
 ++var_name1577;
int var_name1153;
var_name1153 = 0;
var_name772 = var_name1153;
float var_name1151;
int var_name1273;
var_name1273 = 0;
var_name1577 = checkIntInt(var_name1273);
int var_name1015;
var_name1015 = 0;
for( var_name1015 = 12; var_name1015 > 12;var_name1015-- )
{   /* begin block block1012 */
var_name493 = firstarrayr[var_name393];
}   /* end block block1012 */
firstarrayr[var_name106] = 0.0;
var_name231 = var_name992[var_name1015];
printf(">%i<\n", var_name623);
printf(">%i<\n", var_name277);
printf(">%i<\n", firstint);
{   /* begin block block531 */
var_name571 = 0;
var_name145 = var_name95;
}   /* end block block531 */
/* Warn: Assign 4: curpos = 1443, body = var_name277 var_name204 var_name284  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
while( var_name212 != 0 )
{   /* begin block block299 */
var_name7 = 0;
var_name1534 = var_name1534;
 ++var_name591[var_name713];
}   /* end block block299 */
var_name116 = checkIntInt(var_name1251);
 ++var_name704[var_name1191];
firstarrayi[0] = checkIntInt(firstboolean);
var_name623 = checkIntReal(var_name71);
printf(">%i<\n", var_name7);
var_name48 = var_name996[var_name1169];
printf(">%i<\n", var_name77);
var_name145 = var_name17;
var_name7 = firstint;
var_name258 = checkIntInt(var_name225);
var_name666 = checkIntInt(var_name99);
int var_name361;
var_name361 = 0;
for( var_name361 = 42; var_name361 > 48;var_name361-- )
{   /* begin block block358 */
}   /* end block block358 */
/* Warn I2: Increment bad type : curpos =1467, body = firstarrayc var_name131  */
 ++firstarrayc[0];
 ++firstarrayi[firstint];
var_name406 = !(var_name239 == var_name1469[0]);
var_name601 = var_name491;
while( var_name367 != 0 )
{   /* begin block block365 */
var_name69 = !(var_name277 == var_name343);
}   /* end block block365 */
/* Warn: Assign 4: curpos = 1476, body = var_name343 var_name67 var_name17  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
char var_name1678;
printf(">%i<\n", var_name1145);
var_name258 = checkIntInt(var_name343);
 ++firstarrayr[var_name48];
var_name591[0] = checkRealInt(var_name158);
{   /* begin block block1307 */
var_name52 = firstarrayr[var_name626];
{   /* begin block block598 */
var_name214 = !(var_name528 == firstchar);
}   /* end block block598 */
 ++var_name13;
int var_name823;
var_name823 = 0;
for( var_name823 = 17; var_name823 < 18; var_name823++ )
{   /* begin block block820 */
firstint = checkIntInt(firstint);
}   /* end block block820 */
 ++var_name591[var_name815];
}   /* end block block1307 */
var_name149 = 0;
var_name686 = checkIntInt(var_name845);
{   /* begin block block418 */
var_name1015 = checkIntInt(var_name962);
{   /* begin block block1058 */
printf(">%i<\n", var_name145);
var_name1111[0] = checkIntInt(var_name258);
/* Warn: Assign 4: curpos = 1508, body = var_name239 var_name48 var_name160  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
/* Warn: Assign 4: curpos = 1509, body = var_name149 var_name7 var_name158  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
}   /* end block block1058 */
printf(">%i<\n", var_name145);
var_name1111[0] = checkIntInt(var_name258);
/* Warn: Assign 4: curpos = 1513, body = var_name239 var_name48 var_name160  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
int var_name1231;
var_name1231 = 0;
for( var_name1231 = 0; var_name1231 < 1; var_name1231++ )
{   /* begin block block1228 */
int var_name1656;
var_name1656 = 0;
for( var_name1656 = 7; var_name1656 > 19;var_name1656-- )
{   /* begin block block1653 */
/* Warn: Assign 4: curpos = 1518, body = var_name149 var_name7 var_name158  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
var_name95 = checkIntInt(var_name174);
var_name343 = 0;
 ++var_name158;
int var_name731;
var_name731 = 0;
var_name731 = checkIntInt(var_name193);
}   /* end block block1653 */
}   /* end block block1228 */
var_name95 = checkIntInt(var_name174);
var_name343 = 0;
 ++var_name158;
int var_name731;
var_name731 = 0;
var_name731 = checkIntInt(var_name193);
}   /* end block block418 */
var_name21 = checkIntInt(var_name231);
 ++var_name277;
printf(">%i<\n", var_name1111[firstint]);
var_name632 = checkIntInt(var_name681);
while( firstboolean != 0 )
{   /* begin block block24 */
}   /* end block block24 */
var_name451 = !(var_name77 == var_name254);
var_name860 = !(var_name451 == var_name287);
{   /* begin block block1351 */
}   /* end block block1351 */
 ++var_name179;
var_name176 = var_name241[var_name158];
var_name160 = !(var_name694 == var_name632);
int var_name1258;
var_name1258 = 0;
var_name1258 = 0;
var_name69 = firstarrayb[var_name7];
var_name69 = checkBoolInt(var_name30);
 ++var_name277;
var_name1151 = checkRealInt(var_name955);
var_name30 = firstarrayi[var_name7];
while( var_name287 != 0 )
{   /* begin block block413 */
int var_name1042;
var_name1042 = 0;
firstreal = checkRealInt(var_name1042);
var_name974 = var_name720;
int var_name1261;
var_name95 = checkIntInt(firstboolean);
}   /* end block block413 */
var_name59 = 0;
var_name116 = 0;
printf(">%4.2f<\n", firstarrayr[firstint]);
firstarrayb[var_name48] = 0;
printf(">%i<\n", var_name455);
 ++var_name1778[var_name1785];
{   /* begin block block1648 */
int var_name1271;
var_name1271 = 0;
int var_name1511;
var_name1511 = 0;
var_name1511 = !(var_name1271 == var_name328);
var_name99 = var_name825;
var_name678 = !(var_name158 == var_name322);
firstchar = var_name992[var_name836];
int var_name1787[87];
var_name938 = !(var_name700 == var_name865);
firstarrayc[0] = checkCharInt(var_name17);
}   /* end block block1648 */
int var_name1511;
var_name1511 = 0;
var_name1511 = checkIntChar(firstchar);
var_name812 = checkCharReal(var_name1203);
while( var_name593 != 0 )
{   /* begin block block1035 */
int var_name1600;
var_name1600 = 0;
var_name1600 = var_name1310[var_name122];
int var_name1069;
int var_name1646;
var_name1646 = 0;
/* Warn: Assign 4: curpos = 1581, body = var_name343 var_name1646 var_name1698  */
/* Warn: Assign 4: type mismatch 1 & 3 i & i */
/* Err: Assign 4: Dest not an ARRAY! Skipped Code! */
}   /* end block block1035 */
int var_name1042;
var_name1042 = 0;
for( var_name1042 = 10; var_name1042 < 41; var_name1042++ )
{   /* begin block block1039 */
printf(">%i<\n", var_name666);
printf(">%i<\n", firstint);
char var_name1734;
}   /* end block block1039 */
var_name174 = 0;
printf(">%i<\n", var_name996[firstint]);
int var_name731;
var_name731 = 0;
printf(">%i<\n", var_name731);
int var_name1303;
var_name1303 = 0;
var_name1303 = !(var_name1002 == var_name825);
var_name707 = 0;
var_name1668[var_name850] = 0.0;
int var_name1095;
var_name1095 = 0;
while( var_name1095 != 0 )
{   /* begin block block1294 */
while( var_name1487 != 0 )
{   /* begin block block1485 */
var_name149 = 0;
int var_name1404;
firstarrayc[0] = checkCharChar(firstchar);
}   /* end block block1485 */
var_name149 = 0;
int var_name1404;
firstarrayc[0] = checkCharChar(firstchar);
}   /* end block block1294 */
{   /* begin block block1346 */
}   /* end block block1346 */
 ++var_name707;

}  /* end of C program */

/* Function Definitions */

/* ... comment out definitions for now
int   checkIntInt    (int   x) { return x; }
int   checkIntBool   (int   x) { return x; }
int   checkIntChar   (char  x) { return 10; }
int   checkIntReal   (float x) { return 15; }
float checkRealInt   (int   x) { return 10.0; }
float checkRealBool  (int   x) { return 10.0; }
float checkRealChar  (char  x) { return 10.0; }
float checkRealReal  (float x) { return x; }
int   checkBoolInt   (int   x) { return x; }
int   checkBoolBool  (int   x) { return x; }
int   checkBoolChar  (char  x) { return 10; }
int   checkBoolReal  (float x) { return 10; }
char  checkCharInt   (int   x) { return 'a'; }
char  checkCharBool  (int   x) { return 'b'; }
char  checkCharChar  (char  x) { return 'c'; }
char  checkCharReal  (float x) { return 'd'; }

*/ ... end of comment out definitions for now

/* Local Variables: */
/* compile-command: "g++ -ansi -o Sit-q-i2-dist1-default-1000.out Sit-q-i2-dist1-default-1000.c -lm" */
/* End: */
