
(setq *output-stream* t)
;; (setq *debug* nil)

(defun loadt ()
  (load "adt-translate")
  )

(defun testt ()  
  (clear-closure)
  (translate-adt-to-c 'q-i1 'dist1 'default 0 )
  )

(defun tests ()  
  (clear-closure)
  (translate-adt-to-c nil nil nil 99 )
  )

;; ***************************************************************************
;; Start of let - symbol table closure  
;; ***************************************************************************
(let (
      (intlist  '(firstInt))             ;; type symbol tables
      (charlist '(firstChar))
      (reallist '(firstReal))
      (boollist '(firstBool))
      (intAlist  '(firstarrayI))         ;; array symbol tables
      (charAlist '(firstarrayC))
      (realAlist '(firstarrayR))
      (boolAlist '(firstarrayB))
      )
  
(defun translate-adt-to-c ( sit-id rand-dist-id random-ident sit-noise )
  (let* (
	 (adtpart    (concatenate 'string 
				  "Sit-" (string-downcase (string sit-id)) 
				  "-" (string-downcase (string rand-dist-id))
				  "-" (string-downcase (string random-ident))
				  "-" (num-to-string sit-noise) ))
	 (adtfile    (concatenate 'string "ADT-Situation/" adtpart))
	 (cprog-file (concatenate 'string adtfile ".c"))
	 )

    ;; open adtfile
    (if (not (probe-file adtfile))
	(progn
	  (format *output-stream*	"~&> ~A  < ~A > ~& "  
		  "Adtfile does not exist = "  adtfile )
	  (return-from translate-adt-to-c nil)
	  )
      (progn
	(let (
	      (instream     (open adtfile :direct :input))     
	      (cprog-stream nil)
	      (adtsit   nil)
	      )
	  (format *output-stream* "~&> ~A ~& "  "Opened adtfile for input.")  
	  (setq adtsit (read instream))
	  (close instream)

    	  ;; open "C" adtfile for writing by cprog-stream

	  (setq cprog-stream (open cprog-file 
				   :direction :output 
				   :if-exists :overwrite
				   :if-does-not-exist :create))

	  (out-line cprog-stream 
		    "/* This program generated by adt-translate.lisp */ ")

	  ;; define C header
	  (out-line cprog-stream  "main () {")
	  (out-line cprog-stream  "")
	  (out-line cprog-stream 
		    "int DEFAULT_SIZE = 99;  /* define array size */")
	  (out-line cprog-stream  "")
	  (out-line cprog-stream  "/* Initial variable declarations */")

	  ;; define default typed variables
	  (dolist (this intlist) (out-line cprog-stream 
 	    (concatenate 'string "int " (string-downcase this)  " = 0;")))

	  ;; --
	  ;; place special characters in intlist so they are defined
	  (setq intlist	(append '( NULL ) 
				intlist))
	  ;; --


	  (dolist (this boollist) (out-line cprog-stream 
 	    (concatenate 'string "int " (string-downcase this)  " = 0;")))

	  (dolist (this reallist) (out-line cprog-stream 
 	    (concatenate 'string "float " (string-downcase this)  " = 0;")))

	  (dolist (this charlist) (out-line cprog-stream
 	    (concatenate 'string "char " (string-downcase this)  
			 " = \'\\0\';")))

	  ;; define default typed ARRAY variables
	  (out-line cprog-stream  "")
	  (out-line cprog-stream  "/* Initial array declarations */")

	  (dolist (this intAlist) (out-line cprog-stream 
 	    (concatenate 'string 
			 "int " (string-downcase this) "[DEFAULT_SIZE];")))

	  (dolist (this charAlist) (out-line cprog-stream 
 	    (concatenate 'string 
			 "char " (string-downcase this) "[DEFAULT_SIZE];")))

	  (dolist (this realAlist) (out-line cprog-stream 
 	    (concatenate 'string 
			 "float " (string-downcase this) "[DEFAULT_SIZE];")))

	  (dolist (this boolAlist) (out-line cprog-stream 
 	    (concatenate 'string 
			 "int " (string-downcase this) "[DEFAULT_SIZE];")))

	  (out-line cprog-stream  "")
	  (out-line cprog-stream  "/* Initial inline function protoypes */")
	  (out-line cprog-stream  "int   checkIntInt    (int   x);")
	  (out-line cprog-stream  "int   checkIntBool   (int   x);")
	  (out-line cprog-stream  "int   checkIntChar   (char  x);")
	  (out-line cprog-stream  "int   checkIntReal   (float x);")
	  (out-line cprog-stream  "float checkRealInt   (int   x);")
	  (out-line cprog-stream  "float checkRealBool  (int   x);")
	  (out-line cprog-stream  "float checkRealChar  (char  x);")
	  (out-line cprog-stream  "float checkRealReal  (float x);")
	  (out-line cprog-stream  "int   checkBoolInt   (int   x);")
	  (out-line cprog-stream  "int   checkBoolBool  (int   x);")
	  (out-line cprog-stream  "int   checkBoolChar  (char  x);")
	  (out-line cprog-stream  "int   checkBoolReal  (float x);")
	  (out-line cprog-stream  "char  checkCharInt   (int   x);")
	  (out-line cprog-stream  "char  checkCharBool  (int   x);")
	  (out-line cprog-stream  "char  checkCharChar  (char  x);")
	  (out-line cprog-stream  "char  checkCharReal  (float x);")
	  (out-line cprog-stream  "")
	  (out-line cprog-stream  "/* Code parsing commenced ... here. */")
	  (out-line cprog-stream  "")

	  ;; -------------------------------------------------------------

	  (let (
		(curpos 0)    ; current position in adt source 
		(endpos (length adtsit))
		)

	    (comment1 "Starting at curpos = " curpos)
	    (comment1 "Ending   at endpos = " endpos)

	    (loop 

	     (if (= curpos endpos) (return))

;;	     (comment "")
	     (comment1 "curpos now is" curpos)

	     (let*
		 (
		  (curline (nth curpos adtsit))
		  (curid   (first curline))
		  (curplst (second curline))
		  (curstmt (third curline))
		  (curstmttype  (first curstmt))
		  )

	       (comment1 "Processing Statement = " curid)

	       (cond
		
		((eq curstmttype 'decl) 
		 (progn
		   (comment1 "Handling Statement as DECL" curstmt)
		   (process-decl cprog-stream curpos (cdr curstmt))
		   (setq curpos (1+ curpos))
		   ))

		((eq curstmttype 'zero)
		 (progn
		   (comment1 "Handling Statement as ZERO" curstmt)
		   (process-zero cprog-stream curpos (cdr curstmt))
		   (setq curpos (1+ curpos))		   
		   ))

		((eq curstmttype 'increment)
		 (progn
		   (comment1 "Handling Statement as INCREMENT" curstmt)
		   (process-inc cprog-stream curpos (cdr curstmt))
		   (setq curpos (1+ curpos))		   
		   ))

		((eq curstmttype 'assign)
		 (progn
		   (comment1 "Handling Statement as ASSIGN" curstmt)
		   (process-assign cprog-stream curpos (cdr curstmt))
		   (setq curpos (1+ curpos))		   
		   ))

		((eq curstmttype 'check)
		 (progn
		   (comment1 "Handling Statement as CHECK Fn Call" curstmt)
		   (process-check cprog-stream curpos (cdr curstmt))
		   (setq curpos (1+ curpos))		   
		   ))

		((eq curstmttype 'not-equals)
		 (progn
		   (comment1 "Handling Statement as NOT-EQUALS" curstmt)
		   (process-notequals cprog-stream curpos (cdr curstmt))
		   (setq curpos (1+ curpos))		   
		   ))

		((eq curstmttype 'while)
		 (progn
		   (comment1 "Handling Statement as WHILE" curstmt)
		   (setq curpos
			 (process-while cprog-stream curpos (cdr curstmt)))
		   ))
		
		(t (progn
		     (comment1 "Statement Type unhandled: " curstmttype)
		     (setq curpos (1+ curpos))
		     ))

		) ; cond
	       ) ; let*
	     ) ; loop
	    ) ; let
	  
	  ;; -------------------------------------------------------------

	  ;; define C program close
	  (out-line cprog-stream "")
	  (out-line cprog-stream "}  /* end of C program */")
	  (out-line cprog-stream "")
	  (out-line cprog-stream  "/* Function Definitions */")
	  (out-line cprog-stream  "int   checkIntInt    (int   x) { return x; }")
	  (out-line cprog-stream  "int   checkIntBool   (int   x) { return x; }")
	  (out-line cprog-stream  "int   checkIntChar   (char  x) { return 10; }")
	  (out-line cprog-stream  "int   checkIntReal   (float x) { return 15; }")
	  (out-line cprog-stream  "float checkRealInt   (int   x) { return 10.0; }")
	  (out-line cprog-stream  "float checkRealBool  (int   x) { return 10.0; }")
	  (out-line cprog-stream  "float checkRealChar  (char  x) { return 10.0; }")
	  (out-line cprog-stream  "float checkRealReal  (float x) { return x; }")
	  (out-line cprog-stream  "int   checkBoolInt   (int   x) { return x; }")
	  (out-line cprog-stream  "int   checkBoolBool  (int   x) { return x; }")
	  (out-line cprog-stream  "int   checkBoolChar  (char  x) { return 10; }")
	  (out-line cprog-stream  "int   checkBoolReal  (float x) { return 10; }")
	  (out-line cprog-stream  "char  checkCharInt   (int   x) { return \'a\'; }")
	  (out-line cprog-stream  "char  checkCharBool  (int   x) { return \'b\'; }")
	  (out-line cprog-stream  "char  checkCharChar  (char  x) { return \'c\'; }")
	  (out-line cprog-stream  "char  checkCharReal  (float x) { return \'d\'; }")
	  (out-line cprog-stream "")
	  (out-line cprog-stream "/* Local Variables: */")
	  (out-line cprog-stream
		    (concatenate 'string
		    "/* compile-command: \"g++ -ansi -o "
		    adtpart ".out "
		    adtpart ".c -lm\" */"))
	  (out-line cprog-stream "/* End: */")

	  ;; close "C" adtfile for writing by cprog-stream
	  (close cprog-stream)

	  ;; debugging retainers as global

	  (setq *adtsit* adtsit)
	  (setq *intlist* intlist)
	  (setq *charlist* charlist)
	  (setq *reallist* reallist)
	  (setq *boollist* boollist)
	  (setq *intAlist* intAlist)
	  (setq *charAlist* charAlist)
	  (setq *realAlist* realAlist)
	  (setq *boolAlist* boolAlist)

;;    	  (show-list intlist)
;;	  (break)
	  t  ; return t when done
	 )))
      ))

;; ---------------------------------------------------------------------------

(defun process-while (cprog-stream curpos body )


 ; return new curpos
)

(defun process-notequals (cprog-stream curpos body )
  (let* (
	 (part1 (first  body))     
	 (part2 (second body))
	 (part3 (third  body))
	 (type1 (get-var-type part1 1 cprog-stream))
	 (type2 (get-var-type part2 1 cprog-stream))
	 (type3 (get-var-type part3 1 cprog-stream))
	 (name1 (my-downcase part1))
	 (name2 (my-downcase part2))
	 (name3 (my-downcase part3))
	 (field1 (if (member type1 '(ia ra ba ca))
		     (concatenate 'string name1 "[0]") 
		   name1))
	 (field2 (if (member type2 '(ia ra ba ca))
		     (concatenate 'string name2 "[0]") 
		   name2))		     
	 (field3 (if (member type3 '(ia ra ba ca))
		     (concatenate 'string name3 "[0]") 
		   name3))		     
	 )

    (out-line cprog-stream 
	      (concatenate 'string field1 " = \!\(" 
			   field2 " == " field3 "\);"))
    ))

(defun process-check (cprog-stream curpos body )
  (let* (
	 (part1 (first  body))     
	 (part2 (second body))
	 (type1 (get-var-type part1 1 cprog-stream))
	 (type2 (get-var-type part2 1 cprog-stream))
	 (name1 (my-downcase part1))
	 (name2 (my-downcase part2))
	 (ckfnname (get-ckfnname type1 type2))
	 (field1 (if (member type1 '(ia ra ba ca))
		     (concatenate 'string name1 "[0]") 
		   name1))
	 (field2 (if (member type2 '(ia ra ba ca))
		     (concatenate 'string "* " name2)
		   name2))
	 )

    (out-line cprog-stream 
	      (concatenate 'string field1 " = " ckfnname "\(" field2 "\);"))
    ))

(defun process-assign (cprog-stream curpos body )
  (let* (
	 (part1 (first  body))     
	 (part2 (second body))
	 (part3 (third  body))
	 
	 (type1 (get-var-type part1 (- (length body) 1) cprog-stream))  
	                                     ;; one of (i r b c ia ra ba ca)
	                                     ;; undef added as int, i ret'd
	 (type2 (get-var-type part2 1 cprog-stream))
	 (type3 (if part3 
		    (get-var-type part3 1 cprog-stream (get-base-type type1))
		  nil))
	 )

    ; exit on error conditions
    (cond 
     ((member type3 '(ia ra ba ca))
      (progn
	(out-line cprog-stream (concatenate 'string
		  "/* Err: Assign 1: curpos = " (my-downcase curpos) 
		  ", body = " (my-downcase body) " */"))
	(out-line cprog-stream (concatenate 'string
		  "/* Err: Assign 1: error on type3 = " 
		  (my-downcase type3) " */"))
	(comment1 "Process-assign 1: error on type3 = " (my-downcase type3))
	(return-from process-assign nil) ))
     ((and part3 (member type2 '(c r ia ra ba ca)))
      (progn
	(out-line cprog-stream (concatenate 'string
		  "/* Err: Assign 2: curpos = " (my-downcase curpos) 
		  ", body = " (my-downcase body) " */"))
	(out-line cprog-stream (concatenate 'string
		  "/* Err: Assign 2: error on index, type2 = " 
		  (my-downcase type2) " */"))
	(comment1 "Process-assign 2: error on index, type2 = " type2)
	(return-from process-assign nil) ))
     ((and (eq (length body) 2) (not (eq type1 type2)))
      (progn
	(out-line cprog-stream (concatenate 'string
		  "/* Err: Assign 3: curpos = " (my-downcase curpos) 
		  ", body = " (my-downcase body) " */"))
	(out-line cprog-stream (concatenate 'string
		  "/* Err: Assign 3: type mismatch 1 & 2 " (my-downcase type1) 
		  " & " (my-downcase type2) " */"))
	(comment1 "Process-assign 3 : type mismatch type1 = " type1)
	(comment1 "                 : type mismatch type2 = " type2)
	(return-from process-assign nil) ))
     ((and (eq (length body) 3) 
	   (not (member (list type1 type3)
			'( (ia i) (ia b) (ba i) (ba b)
			   (ra r) (ca c) )
			:test #'equal
			)))
      (progn
	(out-line cprog-stream (concatenate 'string
		  "/* Err: Assign 4: curpos = " (my-downcase curpos) 
		  ", body = " (my-downcase body) " */"))
	(out-line cprog-stream (concatenate 'string
		  "/* Err: Assign 4: type mismatch 1 & 3 " (my-downcase type1) 
		  " & " (my-downcase type3) " */"))
	(comment1 "Process-assign 4 : type mismatch type1 = " type1)
	(comment1 "                 : type mismatch type3 = " type3)
	(return-from process-assign nil) ))
     ) ; cond

    (let (
	  (name1 (my-downcase part1))
	  (name2 (my-downcase part2))
	  (name3 (if part3 (my-downcase part3) "NOT REQD"))
	  )

      (cond
       ((eq (length body) 2)
	(progn
	  (out-line cprog-stream (concatenate 'string 
					   name1 " = " name2 ";"))
	  ))
       ((eq (length body) 3)
	(progn
	  (out-line cprog-stream (concatenate 'string 
					   name1 "[" name2 "] = " name3 ";"))
	  ))
       (t 
	(progn
	(out-line cprog-stream (concatenate 'string
		  "/* Err: Assign END: body lngth error : curpos = " 
		  (my-downcase curpos) ", body = " (my-downcase body) " */"))
	(comment1 "Process-assign END : Assign error for body length =" 
		  (length body))
	  ))
       )) ; cond, let
    ))

(defun process-inc (cprog-stream curpos body )
  (let* (
	 (type (get-var-type (first body) (length body) cprog-stream))  
	                                     ;; one of (i r b c ia ra ba ca)
	                                     ;; undef added as int, i ret'd
	 (error (if (member type '(ia ra ba ca))
		    (if (not (eq (get-var-type 
				  (second body) 1 cprog-stream) 'i))
			(progn
			  (out-line cprog-stream (concatenate 'string
  		           "/* Err: Array Incr : curpos =" (my-downcase curpos)
			   ", body = " (my-downcase body) " */"))
			  (comment1 "Error in Increment of array - idx type."  
				    (get-var-type 
				     (second body) 1 cprog-stream))
			  t)
		      nil)
		  nil))
	 )

    (if error (return-from process-inc nil))  ;; exit on error

    (cond 
     ((member type '(ia ra ba))      ; array increment exclude ca
      (let (
	    (arrayname (my-downcase (first  body)))
	    (indexname (my-downcase (second body)))
	    )
	(out-line cprog-stream 			
		  (concatenate 'string arrayname "[" indexname "] = "
    			       arrayname "[" indexname "] + 1;")) ))

     ((member type '(i r b))         ; variable increment exclude c
      (let (
	    (varname (my-downcase (first  body)))
	    )
	(out-line cprog-stream 			
		  (concatenate 'string varname " = " varname " + 1;")) ))

     (t
      (progn
	(out-line cprog-stream (concatenate 'string
            "/* Err: Increment type error : curpos =" (my-downcase curpos)
		  ", body = " (my-downcase body) " */"))
	(comment1 "Process-increment: Increment error on type =" type)
	))
     )
    ))


(defun process-zero (cprog-stream curpos body )
  (let* (
	 (type (get-var-type (first body) (length body) cprog-stream))  
	                                     ;; one of (i r b c ia ra ba ca)
	                                     ;; undef added as int, i ret'd
	 (error (if (member type '(ia ra ba ca))
		    (if (not (eq (get-var-type 
				  (second body) 1 cprog-stream) 'i))
			(progn
			  (out-line cprog-stream (concatenate 'string
		         "/* Err: Zero of array - idx type : curpos =" 
			 (my-downcase curpos) ", body = " 
			 (my-downcase body) " */"))
			  (comment1 "Error in Zero of array - idx type."  
				    (get-var-type 
				     (second body) 1 cprog-stream))
			  t)
		      nil)
		  nil))
	 )

    (if error (return-from process-zero nil))  ;; exit on error

    (cond 
     ((eq type 'i)
      (progn
	(out-line cprog-stream 			
		  (concatenate 'string (my-downcase (first body)) " = 0;"))
	))
     ((eq type 'r)
      (progn
	(out-line cprog-stream 			
		  (concatenate 'string (my-downcase (first body)) " = 0;"))
	))
     ((eq type 'b)
	(out-line cprog-stream 			
		  (concatenate 'string (my-downcase (first body)) " = 0;"))
      (progn
	))
     ((eq type 'c)
      (progn
	(out-line cprog-stream 			
              (concatenate 'string (my-downcase (first body)) " = \'\\0;"))
	))
     ((eq type 'ia)
      (progn
	(out-line cprog-stream 			
		  (concatenate 'string (my-downcase (first body)) "["
			       (my-downcase (second body)) "] = 0;"))
	))
     ((eq type 'ra)
      (progn
	(out-line cprog-stream 			
		  (concatenate 'string (my-downcase (first body)) "["
			       (my-downcase (second body)) "] = 0;"))
	))
     ((eq type 'ba)
      (progn
	(out-line cprog-stream 			
		  (concatenate 'string (my-downcase (first body)) "["
			       (my-downcase (second body)) "] = 0;"))
	))
     ((eq type 'ca)
      (progn
	(out-line cprog-stream 			
		  (concatenate 'string (my-downcase (first body)) "["
			       (my-downcase (second body)) "] = \'\\0;"))
	))
     (t
      (progn
	(out-line cprog-stream (concatenate 'string
  	          "/* Err: ZERO BAD CODE ERROR : curpos =" (my-downcase curpos)
		  ", body = " (my-downcase body) " */"))
	(comment "Process-zero: This statement never reached - error.")
	))
     )))

(defun get-ckfnname (type1 type2)
  (cond
   ((member (list type1 type2) '( (i i) (i ia) (ia i) ) :test #'equal)
            "checkIntInt") 
   ((member (list type1 type2) '( (i b) (i ba) (ia b) (ia ba) ) :test #'equal)
	    "checkIntBool")
   ((member (list type1 type2) '( (i c) (i ca) (ia c) (ia ca) ) :test #'equal) 
            "checkIntChar")
   ((member (list type1 type2) '( (i r) (i ra) (ia r) (ia ra) ) :test #'equal) 
            "checkIntReal")
   ((member (list type1 type2) '( (r i) (r ia) (ra i) (ra ia) ) :test #'equal)
            "checkRealInt") 
   ((member (list type1 type2) '( (r b) (r ba) (ra ba) (ra ba) ) :test #'equal)
	    "checkRealBool")
   ((member (list type1 type2) '( (r c) (r ca) (ra c) (ra ca) )  :test #'equal)
            "checkRealChar")
   ((member (list type1 type2) '( (r r) (r ra) (ra r) ) :test #'equal)       
            "checkRealReal")
   ((member (list type1 type2) '( (b i) (b ia) (ba i) (ba ia) ) :test #'equal)
            "checkBoolInt") 
   ((member (list type1 type2) '( (b b) (b ba) (ba b) ) :test #'equal)
	    "checkBoolBool")
   ((member (list type1 type2) '( (b c) (b ca) (ba c) (ba ca) ) :test #'equal) 
            "checkBoolChar")
   ((member (list type1 type2) '( (b r) (b ra) (ba r) (ba ra) ) :test #'equal) 
            "checkBoolReal")
   ((member (list type1 type2) '( (c i) (c ia) (ca i) (ca ia) ) :test #'equal)
            "checkCharInt") 
   ((member (list type1 type2) '( (c b) (c ba) (ca b) (ca ba) ) :test #'equal)
	    "checkCharBool")
   ((member (list type1 type2) '( (c c) (c ca) (ca c) ) :test #'equal)    
            "checkCharChar")
   ((member (list type1 type2) '( (c r) (c ra) (ca r) (ca ra) ) :test #'equal) 
            "checkCharReal")

   (t "error")
   ))

(defun get-base-type ( type )
  (cond
   ((eq type 'ia) 'i)
   ((eq type 'ba) 'b)
   ((eq type 'ra) 'r)
   ((eq type 'ca) 'c)
   ((eq type 'i)  'i)
   ((eq type 'b)  'b)
   ((eq type 'r)  'r)
   ((eq type 'c)  'c)
   (t (progn
	(comment1 "Error in get-base-type, type = " type) ))
  ))

(defun get-var-type (varname bodylength cprog-stream 
			     &optional (define-special nil))

  (if *debug* (progn
		(comment1 "get-var-type : varname    = " varname)
		(comment1 "             : bodylength = " bodylength)
		(comment1 "             : define-special = " define-special) ))

  (cond 
   ((or (integerp varname) (member varname intlist))  'i)
   ((or (realp    varname) (member varname reallist)) 'r)
   ((member varname boollist) 'b)
   ((member varname charlist) 'c)
   ((member varname intAlist)  'ia)
   ((member varname realAlist) 'ra)
   ((member varname boolAlist) 'ba)
   ((member varname charAlist) 'ca)
   ( define-special
     (let (
	   (type (cond ((eq define-special 'ia) 'int)
		       ((eq define-special 'ba) 'boolean)
		       ((eq define-special 'ra) 'real)
		       ((eq define-special 'ca) 'char) 
	               ((eq define-special 'i) 'int)
		       ((eq define-special 'b) 'boolean)
		       ((eq define-special 'r) 'real)
		       ((eq define-special 'c) 'char) ))
	   (type-is-array (member define-special '(ia ra ba ca)))
	   )

       (if type-is-array
	   (progn
	     (out-line cprog-stream (concatenate 'string
	         (my-downcase type) " " (my-downcase varname) 
		 "[DEFAULT_SIZE];"))
	     )
	 (if (eq type 'char)
	     (progn
	       (out-line cprog-stream (concatenate 'string
		   (my-downcase type) " " (my-downcase varname) " = \'\\0\';"))
	       )
	   (progn
	     (out-line cprog-stream (concatenate 'string
		 (my-downcase type) " " (my-downcase varname) " = 0;"))
	     )))
  
       (var-not-defined varname type type-is-array)

       (if type-is-array
	   (cond ((eq type 'int)  'ia)  ((eq type 'boolean) 'ba) 
		 ((eq type 'real) 'ra)  ((eq type 'char)    'ca) 
	    )
	 (cond ((eq type 'int) 'i)  ((eq type 'boolean) 'b) 
	       ((eq type 'real) 'r) ((eq type 'char) 'c)) )
       ))
   (t (progn                              ; zero var not def - make an int 1st
	(if (= bodylength 1)  ; undef var not an array 
	    (progn
	      (var-not-defined varname 'int)
	      (out-line cprog-stream
			(concatenate 'string 
				     "int " (my-downcase varname) " = 0;"))
	      'i)
	  (progn  ; undef var is an array
	    (var-not-defined varname 'int t)
	    (out-line cprog-stream
		      (concatenate 'string 
				   "int " (my-downcase varname) 
				   "[DEFAULT_SIZE];"))
	    'ia
	    ))))
   ))

(defun process-decl (cprog-stream curpos body )  
  (let (
	(type (first body))
	)
    (if (eq type 'array)
	(let* (
	       (array-name (my-downcase (second body)))
	       (array-type (third body))
	       (array-outtype (cond ((eq array-type 'boolean) 'int)
				    ((eq array-type 'real)    'float)
				    (t                        array-type)))
	       (array-size (fourth body))
	      )

	  (if (var-not-defined (second body) array-type t)
	      (out-line cprog-stream
			(concatenate 'string 
				     (string-downcase array-outtype) " "
				     array-name "["
				     (num-to-string array-size)    "];")))
	  )
      (let* (
	     (var-type (cond  ((eq type 'boolean) 'int)
			      ((eq type 'real)    'float)
			      (t                   type)))
	     (var-name (my-downcase (second body)))
	     )

	(if (var-not-defined (second body) type)
	    (out-line cprog-stream
		      (concatenate 'string 
				   (string-downcase var-type) " "
				   var-name ";")))
	))))


;; ---------------------------------------------------------------------------

(defun var-not-defined (name type &optional (array nil))

  (if *debug* (progn
		(comment1 "var-not-defined: name = " name)
		(comment1 "                 type = " type)
		(comment1 "                 opt array = " array)))

  (if array
      (cond
       ((eq type 'int)
	(if (member name intAlist)
	    nil
	  (progn
	    (if *debug* (comment1 "Adding to intAlist = " name))
	    (setf intAlist (cons name intAlist))
	    t)	  ))
       ((eq type 'real)
	(if (member name realAlist)
	    nil
	  (progn
	    (if *debug* (comment1 "Adding to realAlist = " name))
	    (setf realAlist (cons name realAlist))
	    t) 	  ))
       ((eq type 'char)
	(if (member name charAlist)
	    nil
	  (progn
	    (if *debug* (comment1 "Adding to charAlist = " name))
	    (setf charAlist (cons name charAlist))
	    t) 	  ))
       ((eq type 'boolean)
	(if (member name boolAlist)
	    nil
	  (progn
	    (if *debug* (comment1 "Adding to boolAlist = " name))
	    (setf boolAlist (cons name boolAlist))
	    t) 	  ))
	)
    (cond  ;; not an array just a basic type
       ((eq type 'int)
	(if (member name intlist)
	    nil
	  (progn
	    (if *debug* (comment1 "Adding to intlist = " name))
	    (setf intlist (cons name intlist))
	    t) 	  ))
       ((eq type 'real)
	(if (member name reallist)
	    nil
	  (progn
	    (if *debug* (comment1 "Adding to reallist = " name))
	    (setf reallist (cons name reallist))
	    t) 	  ))
       ((eq type 'char)
	(if (member name charlist)
	    nil
	  (progn
	    (if *debug* (comment1 "Adding to charlist = " name))
	    (setf charlist (cons name charlist))
	    t) 	  ))
       ((eq type 'boolean)
	(if (member name boollist)
	    nil
	  (progn
	    (if *debug* (comment1 "Adding to boollist = " name))
	    (setf boollist (cons name boollist))
	    t) 	  ))
      ))
  ) ; defun close

(defun show-lists ()
  (comment "Intlist = ")  (show-list intlist) 
  (comment "Reallist = ") (show-list reallist) 
  (comment "Charlist = ") (show-list charlist) 
  (comment "Boollist = ") (show-list boollist) 
  (comment "IntAlist = ")  (show-list intAlist) 
  (comment "ReaAllist = ") (show-list realAlist) 
  (comment "CharAlist = ") (show-list charAlist) 
  (comment "BoolAlist = ") (show-list boolAlist) 
  )

(defun clear-closure ()
  (setq intlist '(firstInt))
  (setq charlist '(firstChar))
  (setq reallist '(firstReal))
  (setq boollist '(firstBool))
  (setq intAlist  '(firstarrayI))
  (setq charAlist '(firstarrayC))
  (setq realAlist '(firstarrayR))
  (setq boolAlist '(firstarrayB)) )


;; ***************************************************************************
;; End of let - symbol table closure  
;; ***************************************************************************
) 

(defun my-downcase (name)
    (if (null name)
      ""
    (if (listp name)
	(concatenate 'string (my-downcase (car name)) " " (my-downcase (cdr name)))
      (if (numberp name)
	  (num-to-string name)
	(fix-name (string-downcase name))))))

(defun fix-name (name)
  (let (
	(curpos 0)
	(endpos (length name))
	)
    (if (equal name "real")
	"float"
      (progn
	(loop
	 (if (= curpos endpos) (return))
	 (if (eq (char name curpos) #\-)
	     (setf (char name curpos) #\_))
	 (setq curpos (1+ curpos))
	 )
	name)) ))

(defun out-line (cprog-stream line)
  (format cprog-stream  line)    
  (format cprog-stream  "~1%")   
  )

(defun show-list ( list1 )
  (format *output-stream* "~& List ... ~&")
  (dolist (this list1)
	  (format *output-stream* "Element = ~A ~&" this))
  (format *output-stream* "~& End List. ~&"))

;; ---------------------------------------------------------------------------



    ;; loop through all adtfile program lines

       ;; read a line as: stmtid seqlist stmtstruct

       ;; process line by stmttype = (car stmtstruct)

       ;; case:

           ;; DECL ok

               ;; decl type x      same as type x = ?;
               ;;   ie  bool x = 0;  char x = "";  int x = 0;  real x = 0;

           ;; ZERO ok

               ;; CASE 1
               ;; zero x            same as x = 0;
               ;;  if x defined use it, else define it first

               ;; CASE 2
               ;; zero a idx        same as a[idx] = 0;
               ;;  if idx defined use it, else define, initialize it first
               ;;  if a defined use it, else define it first (rand int,char,bool)

           ;; INCREMENT ok

               ;; CASE 1
               ;; increment x            same as x = x + 1;
               ;;  if x defined use it, else define it first

               ;; CASE 2
               ;; increment a idx        same as a[idx] = a[idx] + 1;
               ;;  if idx defined use it, else define, initialize it first
               ;;  if a defined use it, else define it first (rand int,char,bool)

           ;; ASSIGN ok

               ;; CASE 1 assign x y      same as x = y;
               ;;  if x defined use it, else define it first
               ;;  if y defined use it, else define, initialize it first

               ;; CASE 2 assign a idx x  same as a[idx] = x;
               ;;  if a defined use it, else define it first (rand int,char,bool)
               ;;  if idx defined use it, else define, initialize it first
               ;;  if x defined use it, else define, initialize it first

           ;; CHECK ok

               ;; check x y          same as function call y = check(x)
               ;;  if x defined use it, else define, initialize it first
               ;;  if y defined use it, else define it first

           ;; NOT-EQUALS ok

               ;; not-equals x y z   same as z = not( x == y)
               ;;  if x defined use it, else define, initialize it first
               ;;  if y defined use it, else define, initialize it first
               ;;  if z defined use it, else define, initialize as int first

           ;; WHILE

              ;; CASE 1 - following statement is NOT a begin:

                   ;; translate while (var) as "if (var)"
                   ;; recursively process lines UNTIL begin blockX as 
                   ;;    the interior of the "then" { ... } block
                   ;; next, recursively process lines UNTIL end blockX as
                   ;;    the interior of the "else" { ... } block

              ;; CASE 2 - following statement IS a begin:

                   ;; translate while (var) as "while (var)"
                   ;; recursively process lines BETWEEN begin & end blockX as 
                   ;;    the interior of the "while" { ... } block


;; ---------------------------------------------------------------------------

(defun comment (com )
  (if (not (eq *output-stream* nil))
      (let ()
	(format *output-stream*	"~&> ~A ~& " com)
	))  )

(defun comment1 (com &optional (var nil))
  (if (not (eq *output-stream* nil))
      (let ()
	(format *output-stream*	"~&> ~A " com)
	(format *output-stream* " < ~A > ~&" var)
	)) )


(defun num-to-string ( num )
"
Positive numbers only.
"
(if (< num 10)
    (num-to-letter num)
  (let* (
	 (rest-digits (truncate (/ num 10.0)))
	 (last-digit  (- num (* 10 rest-digits)))
	 )
    
    (concatenate 'string (num-to-string rest-digits) (num-to-letter last-digit) )
    )))

(defun num-to-letter ( num )
  (cond
   ((eq num 0) "0")
   ((eq num 1) "1")
   ((eq num 2) "2")
   ((eq num 3) "3")
   ((eq num 4) "4")
   ((eq num 5) "5")
   ((eq num 6) "6")
   ((eq num 7) "7")
   ((eq num 8) "8")
   ((eq num 9) "9")))

